spring:
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: true
    thymeleaf:
        cache: false
    profiles:
        active: dev
    h2:
        console:
            enabled: true
            path: /h2-console
    datasource:
        url: jdbc:h2:~/db;DB_CLOSE_ON_EXIT=FALSE
        username: sa
        password:
        driver-class-name: org.h2.Driver
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: none
    #liquibase:
#        change-log: classpath:/db/db.changelog.xml
#        enabled: false
    servlet:
        multipart:
            enabled: true
            file-size-threshold: 2KB
            max-file-size: 100MB
            max-request-size: 100MB
#server:
#    servlet:
#        contextPath: /sppi
liquibase:
  change-log: classpath:/db/db.changelog.xml
