import com.egartech.sppi.model.Step;
import com.egartech.sppi.model.Product;

rule "define first question of test"
    when
        product:Product(productCode=="term_susp_oblig");
    then
        product.setFirstQuestionCode("STEP_1");
        update(product);
end

rule "Yes to STEP_1 of test"
    when
        step:Step(current.code=="STEP_1"&&answer=="yes");
    then
        step.setNextQ("STEP_2");
        update(step);
end

rule "No to STEP_1 of test"
    when
        step:Step(current.code=="STEP_1"&&answer=="no");
    then
        step.setNextQ("SUCCESS");
        update(step);
end

rule "Yes_only_cli to STEP_2 of test"
    when
        step:Step(current.code=="STEP_2"&&answer=="yes_only_cli");
    then
        step.setNextQ("STEP_3.1_YES_ONLY_CLI");
        update(step);
end

rule "No_not_only_cli to STEP_2 of test"
    when
        step:Step(current.code=="STEP_2"&&answer=="no_not_only_cli");
    then
        step.setNextQ("STEP_3.1_NO_NOT_ONLY_CLI");
        update(step);
end

rule "No_not_cli to STEP_2 of test"
    when
        step:Step(current.code=="STEP_2"&&answer=="no_not_cli");
    then
        step.setNextQ("STEP_4");
        update(step);
end

rule "Yes to STEP_3.1_NO_NOT_ONLY_CLI of test"
    when
        step:Step(current.code=="STEP_3.1_NO_NOT_ONLY_CLI"&&answer=="yes");
    then
        step.setNextQ("FAIL");
        update(step);
end

rule "No to STEP_3.1_NO_NOT_ONLY_CLI of test"
    when
        step:Step(current.code=="STEP_3.1_NO_NOT_ONLY_CLI"&&answer=="no");
    then
        step.setNextQ("STEP_3.2_NO_NOT_ONLY_CLI");
        update(step);
end

rule "Yes to STEP_3.2_NO_NOT_ONLY_CLI of test"
    when
        step:Step(current.code=="STEP_3.2_NO_NOT_ONLY_CLI"&&answer=="yes");
    then
        step.setNextQ("STEP_3.3_NO_NOT_ONLY_CLI");
        update(step);
end

rule "No to STEP_3.2_NO_NOT_ONLY_CLI of test"
    when
        step:Step(current.code=="STEP_3.2_NO_NOT_ONLY_CLI"&&answer=="no");
    then
        step.setNextQ("FAIL");
        update(step);
end

rule "Yes to STEP_3.3_NO_NOT_ONLY_CLI of test"
    when
        step:Step(current.code=="STEP_3.3_NO_NOT_ONLY_CLI"&&answer=="yes");
    then
        step.setNextQ("STEP_3.4_NO_NOT_ONLY_CLI");
        update(step);
end

rule "No to STEP_3.3_NO_NOT_ONLY_CLI of test"
    when
        step:Step(current.code=="STEP_3.3_NO_NOT_ONLY_CLI"&&answer=="no");
    then
        step.setNextQ("FAIL");
        update(step);
end

rule "Yes to STEP_3.4_NO_NOT_ONLY_CLI of test"
    when
        step:Step(current.code=="STEP_3.4_NO_NOT_ONLY_CLI"&&answer=="yes");
    then
        step.setNextQ("FAIL");
        update(step);
end

rule "No to STEP_3.4_NO_NOT_ONLY_CLI of test"
    when
        step:Step(current.code=="STEP_3.4_NO_NOT_ONLY_CLI"&&answer=="no");
    then
        step.setNextQ("STEP_3.5_NO_NOT_ONLY_CLI");
        update(step);
end

rule "Yes to STEP_3.5_NO_NOT_ONLY_CLI of test"
    when
        step:Step(current.code=="STEP_3.5_NO_NOT_ONLY_CLI"&&answer=="yes");
    then
        step.setNextQ("STEP_4");
        update(step);
end

rule "No to STEP_3.5_NO_NOT_ONLY_CLI of test"
    when
        step:Step(current.code=="STEP_3.5_NO_NOT_ONLY_CLI"&&answer=="no");
    then
        step.setNextQ("STEP_3.6_NO_NOT_ONLY_CLI");
        update(step);
end

rule "Yes to STEP_3.6_NO_NOT_ONLY_CLI of test"
    when
        step:Step(current.code=="STEP_3.6_NO_NOT_ONLY_CLI"&&answer=="yes");
    then
        step.setNextQ("STEP_4");
        update(step);
end

rule "No to STEP_3.6_NO_NOT_ONLY_CLI of test"
    when
        step:Step(current.code=="STEP_3.6_NO_NOT_ONLY_CLI"&&answer=="no");
    then
        step.setNextQ("FAIL");
        update(step);
end

rule "Yes to STEP_4 of test"
    when
        step:Step(current.code=="STEP_4"&&answer=="yes");
    then
        step.setNextQ("SUCCESS");
        update(step);
end

rule "No to STEP_4 of test"
    when
        step:Step(current.code=="STEP_4"&&answer=="no");
    then
        step.setNextQ("STEP_5");
        update(step);
end

rule "Yes to STEP_5 of test"
    when
        step:Step(current.code=="STEP_5"&&answer=="yes");
    then
        step.setNextQ("SUCCESS");
        update(step);
end

rule "No to STEP_5 of test"
    when
        step:Step(current.code=="STEP_5"&&answer=="no");
    then
        step.setNextQ("FAIL");
        update(step);
end

rule "Yes to STEP_3.1_YES_ONLY_CLI of test"
    when
        step:Step(current.code=="STEP_3.1_YES_ONLY_CLI"&&answer=="yes");
    then
        step.setNextQ("FAIL");
        update(step);
end

rule "No to STEP_3.1_YES_ONLY_CLI of test"
    when
        step:Step(current.code=="STEP_3.1_YES_ONLY_CLI"&&answer=="no");
    then
        step.setNextQ("STEP_3.2_YES_ONLY_CLI");
        update(step);
end

rule "Yes to STEP_3.2_YES_ONLY_CLI of test"
    when
        step:Step(current.code=="STEP_3.2_YES_ONLY_CLI"&&answer=="yes");
    then
        step.setNextQ("STEP_3.3_YES_ONLY_CLI");
        update(step);
end

rule "No to STEP_3.2_YES_ONLY_CLI of test"
    when
        step:Step(current.code=="STEP_3.2_YES_ONLY_CLI"&&answer=="no");
    then
        step.setNextQ("FAIL");
        update(step);
end

rule "Yes to STEP_3.3_YES_ONLY_CLI of test"
    when
        step:Step(current.code=="STEP_3.3_YES_ONLY_CLI"&&answer=="yes");
    then
        step.setNextQ("STEP_3.4_YES_ONLY_CLI");
        update(step);
end

rule "No to STEP_3.3_YES_ONLY_CLI of test"
    when
        step:Step(current.code=="STEP_3.3_YES_ONLY_CLI"&&answer=="no");
    then
        step.setNextQ("FAIL");
        update(step);
end

rule "Yes to STEP_3.4_YES_ONLY_CLI of test"
    when
        step:Step(current.code=="STEP_3.4_YES_ONLY_CLI"&&answer=="yes");
    then
        step.setNextQ("FAIL");
        update(step);
end

rule "No to STEP_3.4_YES_ONLY_CLI of test"
    when
        step:Step(current.code=="STEP_3.4_YES_ONLY_CLI"&&answer=="no");
    then
        step.setNextQ("STEP_3.5_YES_ONLY_CLI");
        update(step);
end

rule "Yes to STEP_3.5_YES_ONLY_CLI of test"
    when
        step:Step(current.code=="STEP_3.5_YES_ONLY_CLI"&&answer=="yes");
    then
        step.setNextQ("SUCCESS");
        update(step);
end

rule "No to STEP_3.5_YES_ONLY_CLI of test"
    when
        step:Step(current.code=="STEP_3.5_YES_ONLY_CLI"&&answer=="no");
    then
        step.setNextQ("STEP_3.6_YES_ONLY_CLI");
        update(step);
end

rule "Yes to STEP_3.6_YES_ONLY_CLI of test"
    when
        step:Step(current.code=="STEP_3.6_YES_ONLY_CLI"&&answer=="yes");
    then
        step.setNextQ("SUCCESS");
        update(step);
end

rule "No to STEP_3.6_YES_ONLY_CLI of test"
    when
        step:Step(current.code=="STEP_3.6_YES_ONLY_CLI"&&answer=="no");
    then
        step.setNextQ("FAIL");
        update(step);
end