import com.egartech.sppi.model.Step;
import com.egartech.sppi.model.Product;

rule "define first question of CLE test"
    when
        $product:Product(productCode=="credit_legal_entity");
    then
        $product.setFirstQuestionCode("CLE1");
end

rule "Step CLE1 - YES"
    when
        $step:Step(current.code=="CLE1"&&answer=="yes");
    then
        $step.setNextQ("CLE2");
        
end

rule "Step CLE1 - NO"
    when
        $step:Step(current.code=="CLE1"&&answer=="no");
    then
        $step.setNextQ("CLE6");
        
end

rule "Step CLE2 - YES-Only CLI"
    when
        $step:Step(current.code=="CLE2"&&answer=="yes_only_cli");
    then
        $step.setNextQ("CLE3.1.2");
        
end
rule "Step CLE2 - NO-not only CLI"
    when
        $step:Step(current.code=="CLE2"&&answer=="no_not_only_cli");
    then
        $step.setNextQ("CLE3.1.1");
        
        end
rule "Step CLE2 - NO"
     when
         $step:Step(current.code=="CLE2"&&answer=="no_not_cli");
     then
         $step.setNextQ("CLE4");
         
end
rule "Step CLE3.1.2 - YES"
     when
         $step:Step(current.code=="CLE3.1.2"&&answer=="yes");
     then
        $step.setTestFailed();
        end
rule "Step CLE3.1.2 - NO"
     when
         $step:Step(current.code=="CLE3.1.2"&&answer=="no");
     then
         $step.setNextQ("CLE3.2.2");
         end
rule "Step CLE3.2.2 - YES"
     when
         $step:Step(current.code=="CLE3.2.2"&&answer=="yes");
     then
         $step.setNextQ("CLE3.3.2");
         end
rule "Step CLE3.2.2 - NO"
     when
         $step:Step(current.code=="CLE3.2.2"&&answer=="no");
     then
         $step.setTestFailed();
         end
rule "Step CLE3.3.2 - YES"
     when
         $step:Step(current.code=="CLE3.3.2"&&answer=="yes");
     then
         $step.setNextQ("CLE3.4.2");
         end
rule "Step CLE3.3.2 - NO"
     when
         $step:Step(current.code=="CLE3.3.2"&&answer=="no");
     then
         $step.setTestFailed();
         end
rule "Step CLE3.4.2 - YES"
     when
         $step:Step(current.code=="CLE3.4.2"&&answer=="yes");
     then
         $step.setTestFailed();
         end
rule "Step CLE3.4.2 - NO"
     when
         $step:Step(current.code=="CLE3.4.2"&&answer=="no");
     then
         $step.setNextQ("CLE3.5.2");
         end

rule "Step CLE3.5.2 - YES"
     when
         $step:Step(current.code=="CLE3.5.2"&&answer=="yes");
     then
        $step.setNextQ("CLE6");
        end
rule "Step CLE3.5.2 - NO"
     when
         $step:Step(current.code=="CLE3.5.2"&&answer=="no");
     then
         $step.setNextQ("CLE3.6.2");
         end

 rule "Step CLE3.6.2 - YES"
      when
          $step:Step(current.code=="CLE3.6.2"&&answer=="yes");
      then
         $step.setNextQ("CLE6");
         end
 rule "Step CLE3.6.2 - NO"
      when
          $step:Step(current.code=="CLE3.6.2"&&answer=="no");
      then
         $step.setTestFailed();
         
end

rule "Step CLE3.1.1 - YES"
     when
         $step:Step(current.code=="CLE3.1.1"&&answer=="yes");
     then
        $step.setTestFailed();
        
end
rule "Step CLE3.1.1 - NO"
     when
         $step:Step(current.code=="CLE3.1.1"&&answer=="no");
     then
         $step.setNextQ("CLE3.2.1");
         end
rule "Step CLE3.2.1 - YES"
     when
         $step:Step(current.code=="CLE3.2.1"&&answer=="yes");
     then
         $step.setNextQ("CLE3.3.1");
         end
rule "Step CLE3.2.1 - NO"
     when
         $step:Step(current.code=="CLE3.2.1"&&answer=="no");
     then
         $step.setTestFailed();
         end
rule "Step CLE3.3.1 - YES"
     when
         $step:Step(current.code=="CLE3.3.1"&&answer=="yes");
     then
         $step.setNextQ("CLE3.4.1");
         end
rule "Step CLE3.3.1 - NO"
     when
         $step:Step(current.code=="CLE3.3.1"&&answer=="no");
     then
         $step.setTestFailed();
         end
rule "Step CLE3.4.1 - YES"
     when
         $step:Step(current.code=="CLE3.4.1"&&answer=="yes");
     then
         $step.setTestFailed();
         end
rule "Step CLE3.4.1 - NO"
     when
         $step:Step(current.code=="CLE3.4.1"&&answer=="no");
     then
         $step.setNextQ("CLE3.5.1");
         end

rule "Step CLE3.5.1 - YES"
     when
         $step:Step(current.code=="CLE3.5.1"&&answer=="yes");
     then
        $step.setNextQ("CLE4");
        end
rule "Step CLE3.5.1 - NO"
     when
         $step:Step(current.code=="CLE3.5.1"&&answer=="no");
     then
         $step.setNextQ("CLE3.6.1");
         end

rule "Step CLE3.6.1 - YES"
      when
          $step:Step(current.code=="CLE3.6.1"&&answer=="yes");
      then
         $step.setNextQ("CLE4");
         end
rule "Step CLE3.6.1 - NO"
      when
          $step:Step(current.code=="CLE3.6.1"&&answer=="no");
      then
         $step.setTestFailed();
         end

rule "Step CLE4 - YES"
      when
           $step:Step(current.code=="CLE4"&&answer=="yes");
      then
           $step.setNextQ("CLE6");
           end
rule "Step CLE4 - NO"
      when
            $step:Step(current.code=="CLE4"&&answer=="no");
      then
           $step.setNextQ("CLE5");
           end

rule "Step CLE5 - YES"
      when
           $step:Step(current.code=="CLE5"&&answer=="yes");
      then
           $step.setNextQ("CLE6");
           end
rule "Step CLE5 - NO"
        when
            $step:Step(current.code=="CLE5"&&answer=="no");
        then
             $step.setTestFailed();
             
             end

rule "Step CLE6 - FIXED"
      when
           $step:Step(current.code=="CLE6"&&answer=="fixed");
      then
           $step.setNextQ("CLE8.1");
           end
rule "Step CLE6 - FLOAT"
      when
            $step:Step(current.code=="CLE6"&&answer=="floating");
      then
           $step.setNextQ("CLE7.1");
           end

rule "Step CLE7.1 - YES"
      when
           $step:Step(current.code=="CLE7.1"&&answer=="yes");
      then
           $step.setNextQ("CLE7.2");
           end
rule "Step CLE7.1 - NO"
      when
            $step:Step(current.code=="CLE7.1"&&answer=="no");
      then
             $step.setTestFailed();
             end

rule "Step CLE7.2 - YES"
      when
           $step:Step(current.code=="CLE7.2"&&answer=="yes");
      then
             $step.setTestFailed();
             end
rule "Step CLE7.2 - NO"
      when
            $step:Step(current.code=="CLE7.2"&&answer=="no");
      then
           $step.setNextQ("CLE7.3");
           end
rule "Step CLE7.3 - YES"
      when
           $step:Step(current.code=="CLE7.3"&&answer=="yes");
      then
             $step.setTestFailed();
             end
rule "Step CLE7.3 - NO"
      when
            $step:Step(current.code=="CLE7.3"&&answer=="no");
      then
           $step.setNextQ("CLE7.4");
           end

rule "Step CLE7.4 - YES"
      when
           $step:Step(current.code=="CLE7.4"&&answer=="yes");
      then
           $step.setNextQ("CLE7.5");
           end
rule "Step CLE7.4 - NO"
      when
            $step:Step(current.code=="CLE7.4"&&answer=="no");
      then
             $step.setNextQ("CLE7.7.1");
             end
rule "Step CLE7.5 - YES"
      when
           $step:Step(current.code=="CLE7.5"&&answer=="yes");
      then
           $step.setNextQ("CLE7.6");
           end
rule "Step CLE7.5 - NO"
      when
            $step:Step(current.code=="CLE7.5"&&answer=="no");
      then
           $step.setNextQ("CLE7.7.1");
           end
rule "Step CLE7.6 - YES"
      when
           $step:Step(current.code=="CLE7.6"&&answer=="yes");
      then
           $step.setNextQ("CLE7.7.1");
           end
rule "Step CLE7.6 - NO"
      when
            $step:Step(current.code=="CLE7.6"&&answer=="no");
      then
           $step.setNextQ("CLE8.1");
           end

rule "Step CLE7.7.1 - YES"
      when
           $step:Step(current.code=="CLE7.7.1"&&answer=="yes");
      then
           $step.setNextQ("CLE8.1");
           end
rule "Step CLE7.7.1 - NO"
      when
            $step:Step(current.code=="CLE7.7.1"&&answer=="no");
      then
           $step.setNextQ("CLE7.7.2");
           end

rule "Step CLE7.7.2 - YES"
      when
           $step:Step(current.code=="CLE7.7.2"&&answer=="yes");
      then
           $step.setTestFailed();
           
end
rule "Step CLE7.7.2 - NO"
      when
            $step:Step(current.code=="CLE7.7.2"&&answer=="no");
      then
           $step.setNextQ("CLE8.1");
           
end

rule "Step CLE8.1 - YES"
      when
           $step:Step(current.code=="CLE8.1"&&answer=="yes");
      then
           $step.setNextQ("CLE8.2.2");
           end
rule "Step CLE8.1 - NO(with_condition)"
      when
            $step:Step(current.code=="CLE8.1"&&answer=="no_with_condition");
      then
           $step.setNextQ("CLE8.2.1");
           end

 rule "Step CLE8.1 - NO(with_steps)"
       when
             $step:Step(current.code=="CLE8.1"&&answer=="no_with_step");
       then
            $step.setNextQ("CLE9.1");
            end

rule "Step CLE8.1 - NO (not condition)"
      when
           $step:Step(current.code=="CLE8.1"&&answer=="no_not_condition");
      then
           $step.setNextQ("CLE10");
           end


rule "Step CLE8.2.1 - YES"
      when
            $step:Step(current.code=="CLE8.2.1"&&answer=="yes");
      then
           $step.setNextQ("CLE9.1");
           end

rule "Step CLE8.2.1 - NO"
      when
            $step:Step(current.code=="CLE8.2.1"&&answer=="no");
      then
           $step.setTestFailed();
           end
rule "Step CLE8.2.2 - YES"
      when
            $step:Step(current.code=="CLE8.2.2"&&answer=="yes");
      then
           $step.setNextQ("CLE10");
           end

rule "Step CLE8.2.2 - NO"
      when
            $step:Step(current.code=="CLE8.2.2"&&answer=="no");
      then
           $step.setTestFailed();
           end

rule "Step CLE9.1 - YES"
      when
            $step:Step(current.code=="CLE9.1"&&answer=="yes");
      then
           $step.setNextQ("CLE9.2");
           end
rule "Step CLE9.1 - NO"
      when
            $step:Step(current.code=="CLE9.1"&&answer=="no");
      then
           $step.setNextQ("CLE9.2");
           end
rule "Step CLE9.2 - YES"
      when
            $step:Step(current.code=="CLE9.2"&&answer=="yes");
      then
           $step.setNextQ("CLE9.3");
           end
rule "Step CLE9.2 - NO"
      when
            $step:Step(current.code=="CLE9.2"&&answer=="no");
      then
           $step.setNextQ("CLE9.3");
           
end

rule "Step CLE9.3 - YES"
      when
            $step:Step(current.code=="CLE9.3"&&answer=="yes");
      then
           $step.setNextQ("CLE9.3.1");
           
end
rule "Step CLE9.3 - NO"
      when
            $step:Step(current.code=="CLE9.3"&&answer=="no");
      then
           $step.setNextQ("CLE9.4");
           end

rule "Step CLE9.3.1 - YES"
      when
            $step:Step(current.code=="CLE9.3.1"&&answer=="yes");
      then
           $step.setNextQ("CLE9.4");
           end
rule "Step CLE9.3.1 - NO"
      when
            $step:Step(current.code=="CLE9.3.1"&&answer=="no");
      then
           $step.setNextQ("CLE9.3.2");
           end

rule "Step CLE9.3.2 - YES"
      when
            $step:Step(current.code=="CLE9.3.2"&&answer=="yes");
      then
           $step.setNextQ("CLE9.4");
           end
rule "Step CLE9.3.2 - NO"
      when
            $step:Step(current.code=="CLE9.3.2"&&answer=="no");
      then
           $step.setNextQ("CLE9.3.3");
           end

rule "Step CLE9.3.3 - YES"
      when
            $step:Step(current.code=="CLE9.3.3"&&answer=="yes");
      then
           $step.setNextQ("CLE9.4");
           end
rule "Step CLE9.3.3 - NO"
      when
            $step:Step(current.code=="CLE9.3.3"&&answer=="no");
      then
            $step.setTestFailed();
           end
rule "Step CLE9.4 - YES"
      when
            $step:Step(current.code=="CLE9.4"&&answer=="yes");
      then
            $step.setTestFailed();
            end
rule "Step CLE9.4 - NO"
      when
            $step:Step(current.code=="CLE9.4"&&answer=="no");
      then
           $step.setNextQ("CLE9.5");
           end

rule "Step CLE9.5 - YES"
      when
            $step:Step(current.code=="CLE9.5"&&answer=="yes");
      then
            $step.setTestFailed();
            end
rule "Step CLE9.5 - NO"
      when
            $step:Step(current.code=="CLE9.5"&&answer=="no");
      then
           $step.setNextQ("CLE9.6");
           end

rule "Step CLE9.6 - YES"
      when
            $step:Step(current.code=="CLE9.6"&&answer=="yes");
      then
           $step.setNextQ("CLE9.6.1");
           end
rule "Step CLE9.6 - NO"
      when
            $step:Step(current.code=="CLE9.6"&&answer=="no");
      then
           $step.setNextQ("CLE10");
           end

rule "Step CLE9.6.1 - YES"
      when
            $step:Step(current.code=="CLE9.6.1"&&answer=="yes");
      then
           $step.setNextQ("CLE10");
           end
rule "Step CLE9.6.1 - NO"
      when
            $step:Step(current.code=="CLE9.6.1"&&answer=="no");
      then
            $step.setTestFailed();
           end
rule "Step CLE10 - YES"
      when
            $step:Step(current.code=="CLE10"&&answer=="yes");
      then
           $step.setNextQ("CLE11");
           end
rule "Step CLE10 - NO"
      when
            $step:Step(current.code=="CLE10"&&answer=="no");
      then
           $step.setNextQ("CLE15");
           end

rule "Step CLE11 - YES"
      when
            $step:Step(current.code=="CLE11"&&answer=="yes");
      then
           $step.setNextQ("CLE14.1");
           end
rule "Step CLE11 - NO"
      when
            $step:Step(current.code=="CLE11"&&answer=="no");
      then
           $step.setNextQ("CLE12");
           end

rule "Step CLE12 - YES"
      when
            $step:Step(current.code=="CLE12"&&answer=="yes");
      then
           $step.setNextQ("CLE15");
           end
rule "Step CLE12 - NO"
      when
            $step:Step(current.code=="CLE12"&&answer=="no");
      then
           $step.setNextQ("CLE13.1");
           end

rule "Step CLE13.1 - YES"
      when
            $step:Step(current.code=="CLE13.1"&&answer=="yes");
      then
           $step.setNextQ("CLE13.2");
           end
rule "Step CLE13.1 - NO"
      when
            $step:Step(current.code=="CLE13.1"&&answer=="no");
      then
           $step.setNextQ("CLE13.2");
           end

rule "Step CLE13.2 - YES"
      when
            $step:Step(current.code=="CLE13.2"&&answer=="yes");
      then
           $step.setNextQ("CLE13.3");
           end
rule "Step CLE13.2 - NO"
      when
            $step:Step(current.code=="CLE13.2"&&answer=="no");
      then
           $step.setNextQ("CLE13.3");
           end

rule "Step CLE13.3 - YES"
      when
            $step:Step(current.code=="CLE13.3"&&answer=="yes");
      then
           $step.setNextQ("CLE13.4");
           end
rule "Step CLE13.3 - NO"
      when
            $step:Step(current.code=="CLE13.3"&&answer=="no");
      then
           $step.setNextQ("CLE13.4");
           end

rule "Step CLE13.4 - YES"
      when
            $step:Step(current.code=="CLE13.4"&&answer=="yes");
      then
            $step.setTestFailed();
            end
rule "Step CLE13.4 - NO"
      when
            $step:Step(current.code=="CLE13.4"&&answer=="no");
      then
           $step.setNextQ("CLE13.5");
           end
rule "Step CLE13.5 - YES"
      when
            $step:Step(current.code=="CLE13.5"&&answer=="yes");
      then
            $step.setTestFailed();
            end
rule "Step CLE13.5 - NO"
      when
            $step:Step(current.code=="CLE13.5"&&answer=="no");
      then
           $step.setNextQ("CLE13.6");
           end
rule "Step CLE13.6 - YES"
      when
            $step:Step(current.code=="CLE13.6"&&answer=="yes");
      then
           $step.setNextQ("CLE13.6.1");
           end
rule "Step CLE13.6 - NO"
      when
            $step:Step(current.code=="CLE13.6"&&answer=="no");
      then
           $step.setNextQ("CLE15");
           end
rule "Step CLE13.6.1 - YES"
      when
            $step:Step(current.code=="CLE13.6.1"&&answer=="yes");
      then
           $step.setNextQ("CLE15");
           end
rule "Step CLE13.6.1 - NO"
      when
            $step:Step(current.code=="CLE13.6.1"&&answer=="no");
      then
            $step.setTestFailed();
           end

rule "Step CLE14.1 - YES"
      when
            $step:Step(current.code=="CLE14.1"&&answer=="yes");
      then
           $step.setNextQ("CLE14.4");
           end
rule "Step CLE14.1 - NO"
      when
            $step:Step(current.code=="CLE14.1"&&answer=="no");
      then
           $step.setNextQ("CLE14.2");
           end

rule "Step CLE14.2 - YES"
      when
            $step:Step(current.code=="CLE14.2"&&answer=="yes");
      then
           $step.setNextQ("CLE14.4");
           end
rule "Step CLE14.2 - NO"
      when
            $step:Step(current.code=="CLE14.2"&&answer=="no");
      then
           $step.setNextQ("CLE14.3");
           end

rule "Step CLE14.3 - YES"
      when
            $step:Step(current.code=="CLE14.3"&&answer=="yes");
      then
           $step.setNextQ("CLE14.4");
           end
rule "Step CLE14.3 - NO"
      when
            $step:Step(current.code=="CLE14.3"&&answer=="no");
      then
           $step.setNextQ("CLE12");
           end

rule "Step CLE14.4 - YES"
      when
            $step:Step(current.code=="CLE14.4"&&answer=="yes");
      then
           $step.setNextQ("CLE12");
           end
rule "Step CLE14.4 - NO"
      when
            $step:Step(current.code=="CLE14.4"&&answer=="no");
      then
            $step.setTestFailed();
            end
rule "Step CLE15 - YES"
      when
            $step:Step(current.code=="CLE15"&&answer=="yes");
      then
           $step.setNextQ("CLE16");
           end
rule "Step CLE15 - NO"
      when
            $step:Step(current.code=="CLE15"&&answer=="no");
      then
           $step.setNextQ("CLE24");
           end

rule "Step CLE16 - YES"
      when
            $step:Step(current.code=="CLE16"&&answer=="yes");
      then
           $step.setNextQ("CLE24");
           end
rule "Step CLE16 - NO"
      when
            $step:Step(current.code=="CLE16"&&answer=="no");
      then
           $step.setNextQ("CLE17");
           end

rule "Step CLE17 - YES"
      when
            $step:Step(current.code=="CLE17"&&answer=="yes");
      then
           $step.setNextQ("CLE24");
           end
rule "Step CLE17 - NO"
      when
            $step:Step(current.code=="CLE17"&&answer=="no");
      then
           $step.setNextQ("CLE18");
           end


rule "Step CLE18 - FIXED"
      when
           $step:Step(current.code=="CLE18"&&answer=="fixed");
      then
           $step.setNextQ("CLE20.1");
           end
rule "Step CLE18 - FLOAT"
      when
            $step:Step(current.code=="CLE18"&&answer=="floating");
      then
           $step.setNextQ("CLE19.1");
           end

rule "Step CLE19.1 - YES"
      when
           $step:Step(current.code=="CLE19.1"&&answer=="yes");
      then
           $step.setNextQ("CLE19.2");
           end
rule "Step CLE19.1 - NO"
      when
            $step:Step(current.code=="CLE19.1"&&answer=="no");
      then
           $step.setTestFailed();
           end
rule "Step CLE19.2 - YES"
      when
           $step:Step(current.code=="CLE19.2"&&answer=="yes");
      then
             $step.setTestFailed();
             end
rule "Step CLE19.2 - NO"
      when
            $step:Step(current.code=="CLE19.2"&&answer=="no");
      then
           $step.setNextQ("CLE19.3");
           end
rule "Step CLE19.3 - YES"
      when
           $step:Step(current.code=="CLE19.3"&&answer=="yes");
      then
           $step.setTestFailed();
           end
rule "Step CLE19.3 - NO"
      when
            $step:Step(current.code=="CLE19.3"&&answer=="no");
      then
           $step.setNextQ("CLE19.4");
           end

rule "Step CLE19.4 - YES"
      when
           $step:Step(current.code=="CLE19.4"&&answer=="yes");
      then
           $step.setNextQ("CLE19.5");
           end
rule "Step CLE19.4 - NO"
      when
            $step:Step(current.code=="CLE19.4"&&answer=="no");
      then
             $step.setNextQ("CLE19.7.1");
             end
rule "Step CLE19.5 - YES"
      when
           $step:Step(current.code=="CLE19.5"&&answer=="yes");
      then
           $step.setNextQ("CLE19.6");
           end
rule "Step CLE19.5 - NO"
      when
            $step:Step(current.code=="CLE19.5"&&answer=="no");
      then
           $step.setNextQ("CLE19.7.1");
           end
rule "Step CLE19.6 - YES"
      when
           $step:Step(current.code=="CLE19.6"&&answer=="yes");
      then
           $step.setNextQ("CLE19.7.1");
           end
rule "Step CLE19.6 - NO"
      when
            $step:Step(current.code=="CLE19.6"&&answer=="no");
      then
           $step.setNextQ("CLE20.1");
           end

rule "Step CLE19.7.1 - YES"
      when
           $step:Step(current.code=="CLE19.7.1"&&answer=="yes");
      then
           $step.setNextQ("CLE20.1");
           end
rule "Step CLE19.7.1 - NO"
      when
            $step:Step(current.code=="CLE19.7.1"&&answer=="no");
      then
           $step.setNextQ("CLE19.7.2");
           end

rule "Step CLE19.7.2 - YES"
      when
           $step:Step(current.code=="CLE19.7.2"&&answer=="yes");
      then
           $step.setTestFailed();
           end
rule "Step CLE19.7.2 - NO"
      when
            $step:Step(current.code=="CLE19.7.2"&&answer=="no");
      then
           $step.setNextQ("CLE20.1");
           end

rule "Step CLE20.1 - YES"
      when
           $step:Step(current.code=="CLE20.1"&&answer=="yes");
      then
           $step.setNextQ("CLE20.2.2");
           end
rule "Step CLE20.1 - NO(with_condition)"
      when
            $step:Step(current.code=="CLE20.1"&&answer=="no_with_condition");
      then
           $step.setNextQ("CLE20.2.1");
           end
   rule "Step CLE20.1 - NO(with_steps)"
         when
               $step:Step(current.code=="CLE20.1"&&answer=="no_with_step");
         then
              $step.setNextQ("CLE21.1");
              end

rule "Step CLE20.1 - NO (not condition)"
      when
           $step:Step(current.code=="CLE20.1"&&answer=="no_not_condition");
      then
           $step.setNextQ("CLE22");
           end


rule "Step CLE20.2.1 - YES"
      when
            $step:Step(current.code=="CLE20.2.1"&&answer=="yes");
      then
           $step.setNextQ("CLE21.1");
           end

rule "Step CLE20.2.1 - NO"
      when
            $step:Step(current.code=="CLE20.2.1"&&answer=="no");
      then
           $step.setTestFailed();
           end
rule "Step CLE20.2.2 - YES"
      when
            $step:Step(current.code=="CLE20.2.2"&&answer=="yes");
      then
           $step.setNextQ("CLE22");
           end

rule "Step CLE20.2.2 - NO"
      when
            $step:Step(current.code=="CLE20.2.2"&&answer=="no");
      then
           $step.setTestFailed();
           end

rule "Step CLE21.1 - YES"
      when
            $step:Step(current.code=="CLE21.1"&&answer=="yes");
      then
           $step.setNextQ("CLE21.2");
           end
rule "Step CLE21.1 - NO"
      when
            $step:Step(current.code=="CLE21.1"&&answer=="no");
      then
           $step.setNextQ("CLE21.2");
           end
rule "Step CLE21.2 - YES"
      when
            $step:Step(current.code=="CLE21.2"&&answer=="yes");
      then
           $step.setNextQ("CLE21.3");
           end
rule "Step CLE21.2 - NO"
      when
            $step:Step(current.code=="CLE21.2"&&answer=="no");
      then
           $step.setNextQ("CLE21.3");
           end

rule "Step CLE21.3 - YES"
      when
            $step:Step(current.code=="CLE21.3"&&answer=="yes");
      then
           $step.setNextQ("CLE21.3.1");
           end
rule "Step CLE21.3 - NO"
      when
            $step:Step(current.code=="CLE21.3"&&answer=="no");
      then
           $step.setNextQ("CLE21.4");
           end

rule "Step CLE21.3.1 - YES"
      when
            $step:Step(current.code=="CLE21.3.1"&&answer=="yes");
      then
           $step.setNextQ("CLE21.4");
           end
rule "Step CLE21.3.1 - NO"
      when
            $step:Step(current.code=="CLE21.3.1"&&answer=="no");
      then
           $step.setNextQ("CLE21.3.2");
           end

rule "Step CLE21.3.2 - YES"
      when
            $step:Step(current.code=="CLE21.3.2"&&answer=="yes");
      then
           $step.setNextQ("CLE21.4");
           end
rule "Step CLE21.3.2 - NO"
      when
            $step:Step(current.code=="CLE21.3.2"&&answer=="no");
      then
           $step.setNextQ("CLE21.3.3");
           end

rule "Step CLE21.3.3 - YES"
      when
            $step:Step(current.code=="CLE21.3.3"&&answer=="yes");
      then
           $step.setNextQ("CLE21.4");
           end
rule "Step CLE21.3.3 - NO"
      when
            $step:Step(current.code=="CLE21.3.3"&&answer=="no");
      then
            $step.setTestFailed();
            end
rule "Step CLE21.4 - YES"
      when
            $step:Step(current.code=="CLE21.4"&&answer=="yes");
      then
            $step.setTestFailed();
            end
rule "Step CLE21.4 - NO"
      when
            $step:Step(current.code=="CLE21.4"&&answer=="no");
      then
           $step.setNextQ("CLE21.5");
           end

rule "Step CLE21.5 - YES"
      when
            $step:Step(current.code=="CLE21.5"&&answer=="yes");
      then
            $step.setTestFailed();
            end
rule "Step CLE21.5 - NO"
      when
            $step:Step(current.code=="CLE21.5"&&answer=="no");
      then
           $step.setNextQ("CLE21.6");
           end

rule "Step CLE21.6 - YES"
      when
            $step:Step(current.code=="CLE21.6"&&answer=="yes");
      then
           $step.setNextQ("CLE21.6.1");
           end
rule "Step CLE21.6 - NO"
      when
            $step:Step(current.code=="CLE21.6"&&answer=="no");
      then
           $step.setNextQ("CLE22");
           end

rule "Step CLE21.6.1 - YES"
      when
            $step:Step(current.code=="CLE21.6.1"&&answer=="yes");
      then
           $step.setNextQ("CLE22");
           end
rule "Step CLE21.6.1 - NO"
      when
            $step:Step(current.code=="CLE21.6.1"&&answer=="no");
      then
            $step.setTestFailed();
            end


rule "Step CLE22 - YES"
      when
            $step:Step(current.code=="CLE22"&&answer=="yes");
      then
           $step.setNextQ("CLE23");
           end
rule "Step CLE22 - NO"
      when
            $step:Step(current.code=="CLE22"&&answer=="no");
      then
           $step.setNextQ("CLE24");
           end

rule "Step CLE23 - YES"
      when
            $step:Step(current.code=="CLE23"&&answer=="yes");
      then
           $step.setNextQ("CLE24");
           end
rule "Step CLE23 - NO"
      when
            $step:Step(current.code=="CLE23"&&answer=="no");
      then
           $step.setNextQ("CLE23.1");
           end

rule "Step CLE23.1 - YES"
      when
            $step:Step(current.code=="CLE23.1"&&answer=="yes");
      then
           $step.setNextQ("CLE23.2");
           end
rule "Step CLE23.1 - NO"
      when
            $step:Step(current.code=="CLE23.1"&&answer=="no");
      then
           $step.setNextQ("CLE23.2");
           end
rule "Step CLE23.2 - YES"
      when
            $step:Step(current.code=="CLE23.2"&&answer=="yes");
      then
            $step.setTestFailed();
            end
rule "Step CLE23.2 - NO"
      when
            $step:Step(current.code=="CLE23.2"&&answer=="no");
      then
           $step.setNextQ("CLE23.3");
           end

rule "Step CLE23.3 - YES"
      when
            $step:Step(current.code=="CLE23.3"&&answer=="yes");
      then
           $step.setNextQ("CLE23.3.1");
           end
rule "Step CLE23.3 - NO"
      when
            $step:Step(current.code=="CLE23.3"&&answer=="no");
      then
           $step.setNextQ("CLE24");
           end

rule "Step CLE23.3.1 - YES"
      when
            $step:Step(current.code=="CLE23.3.1"&&answer=="yes");
      then
           $step.setNextQ("CLE24");
           end
rule "Step CLE23.3.1 - NO"
      when
            $step:Step(current.code=="CLE23.3.1"&&answer=="no");
      then
            $step.setTestFailed();
            end

rule "Step CLE24 - YES"
      when
            $step:Step(current.code=="CLE24"&&answer=="yes");
      then
           $step.setNextQ("CLE30");
           end
rule "Step CLE24 - NO"
      when
            $step:Step(current.code=="CLE24"&&answer=="no");
      then
           $step.setNextQ("CLE25");
           end

rule "Step CLE25 - YES"
      when
            $step:Step(current.code=="CLE25"&&answer=="yes");
      then
           $step.setNextQ("CLE26");
           end
rule "Step CLE25 - NO"
      when
            $step:Step(current.code=="CLE25"&&answer=="no");
      then
           $step.setNextQ("CLE30");
           end
rule "Step CLE26 - YES"
      when
            $step:Step(current.code=="CLE26"&&answer=="yes");
      then
           $step.setNextQ("CLE27");
           end
rule "Step CLE26 - NO"
      when
            $step:Step(current.code=="CLE26"&&answer=="no");
      then
           $step.setNextQ("CLE28.1");
           end

rule "Step CLE27 - YES"
      when
            $step:Step(current.code=="CLE27"&&answer=="yes");
      then
           $step.setNextQ("CLE28.1");
           end
rule "Step CLE27 - NO"
      when
            $step:Step(current.code=="CLE27"&&answer=="no");
      then
           $step.setNextQ("CLE30");
           end

rule "Step CLE28.1 - YES"
      when
            $step:Step(current.code=="CLE28.1"&&answer=="yes");
      then
           $step.setNextQ("CLE28.2");
           end
rule "Step CLE28.1 - NO"
      when
            $step:Step(current.code=="CLE28.1"&&answer=="no");
      then
           $step.setNextQ("CLE28.3");
           end

rule "Step CLE28.2 - YES"
      when
            $step:Step(current.code=="CLE28.2"&&answer=="yes");
      then
           $step.setNextQ("CLE30");
           end
rule "Step CLE28.2 - NO"
      when
            $step:Step(current.code=="CLE28.2"&&answer=="no");
      then
           $step.setNextQ("CLE28.3");
           end

rule "Step CLE28.3 - YES"
      when
            $step:Step(current.code=="CLE28.3"&&answer=="yes");
      then
           $step.setNextQ("CLE30");
           end
rule "Step CLE28.3 - NO"
      when
            $step:Step(current.code=="CLE28.3"&&answer=="no");
      then
           $step.setNextQ("CLE29");
           end

rule "Step CLE29 - YES"
      when
            $step:Step(current.code=="CLE29"&&answer=="yes");
      then
           $step.setNextQ("CLE29.1");
           end
rule "Step CLE29 - NO"
      when
            $step:Step(current.code=="CLE29"&&answer=="no");
      then
            $step.setTestFailed();
            end
rule "Step CLE29.1 - YES"
      when
            $step:Step(current.code=="CLE29.1"&&answer=="yes");
      then
           $step.setNextQ("CLE30");
           end
rule "Step CLE29.1 - NO"
      when
            $step:Step(current.code=="CLE29.1"&&answer=="no");
      then
            $step.setTestFailed();
            end
 rule "Step CLE30 - YES"
       when
             $step:Step(current.code=="CLE30"&&answer=="yes");
       then
            $step.setNextQ("CLE31");
            end
 rule "Step CLE30 - NO"
       when
             $step:Step(current.code=="CLE30"&&answer=="no");
       then
            $step.setNextQ("CLE36");
            end

 rule "Step CLE31 - YES"
       when
             $step:Step(current.code=="CLE31"&&answer=="yes");
       then
            $step.setNextQ("CLE39");
            end
 rule "Step CLE31 - NO"
       when
             $step:Step(current.code=="CLE31"&&answer=="no");
       then
            $step.setNextQ("CLE32");
            end

 rule "Step CLE32 - YES"
       when
             $step:Step(current.code=="CLE32"&&answer=="yes");
       then
            $step.setNextQ("CLE33");
            end
 rule "Step CLE32 - NO"
       when
             $step:Step(current.code=="CLE32"&&answer=="no");
       then
            $step.setNextQ("CLE39");
            end

 rule "Step CLE33 - YES"
       when
             $step:Step(current.code=="CLE33"&&answer=="yes");
       then
            $step.setNextQ("CLE36");
            end
 rule "Step CLE33 - NO"
       when
             $step:Step(current.code=="CLE33"&&answer=="no");
       then
            $step.setNextQ("CLE34");
            end

 rule "Step CLE34 - YES"
       when
             $step:Step(current.code=="CLE34"&&answer=="yes");
       then
            $step.setTestFailed();
            end
 rule "Step CLE34 - NO"
       when
             $step:Step(current.code=="CLE34"&&answer=="no");
       then
            $step.setNextQ("CLE35.1");
            end


rule "Step CLE35.1 - YES"
       when
             $step:Step(current.code=="CLE35.1"&&answer=="yes");
       then
            $step.setNextQ("CLE35.2");
            end
rule "Step CLE35.1 - NO"
       when
             $step:Step(current.code=="CLE35.1"&&answer=="no");
       then
            $step.setNextQ("CLE35.2");
            end

rule "Step CLE35.2 - YES"
       when
             $step:Step(current.code=="CLE35.2"&&answer=="yes");
       then
            $step.setNextQ("CLE35.3");
            end
rule "Step CLE35.2 - NO"
       when
             $step:Step(current.code=="CLE35.2"&&answer=="no");
       then
            $step.setNextQ("CLE35.3");
            end
rule "Step CLE35.3 - YES"
        when
              $step:Step(current.code=="CLE35.3"&&answer=="yes");
        then
             $step.setNextQ("CLE35.3.1");
             end
rule "Step CLE35.3 - NO"
        when
              $step:Step(current.code=="CLE35.3"&&answer=="no");
        then
             $step.setNextQ("CLE35.4");
             end
 rule "Step CLE35.3.1 - YES"
       when
             $step:Step(current.code=="CLE35.3.1"&&answer=="yes");
       then
            $step.setNextQ("CLE35.4");
            end
 rule "Step CLE35.3.1 - NO"
       when
             $step:Step(current.code=="CLE35.3.1"&&answer=="no");
       then
            $step.setNextQ("CLE35.3.2");
            end

 rule "Step CLE35.3.2 - YES"
       when
             $step:Step(current.code=="CLE35.3.2"&&answer=="yes");
       then
            $step.setNextQ("CLE35.4");
            end
 rule "Step CLE35.3.2 - NO"
       when
             $step:Step(current.code=="CLE35.3.2"&&answer=="no");
       then
            $step.setNextQ("CLE35.3.3");
            end
 rule "Step CLE35.3.3 - YES"
       when
             $step:Step(current.code=="CLE35.3.3"&&answer=="yes");
       then
            $step.setNextQ("CLE35.4");
            end
 rule "Step CLE35.3.3 - NO"
       when
             $step:Step(current.code=="CLE35.3.3"&&answer=="no");
       then
            $step.setTestFailed();
            end
rule "Step CLE35.4 - YES"
       when
             $step:Step(current.code=="CLE35.4"&&answer=="yes");
       then
            $step.setTestFailed();
             end
rule "Step CLE35.4 - NO"
       when
             $step:Step(current.code=="CLE35.4"&&answer=="no");
       then
             $step.setNextQ("CLE35.5");
             end

rule "Step CLE35.5 - YES"
       when
             $step:Step(current.code=="CLE35.5"&&answer=="yes");
       then
             $step.setNextQ("CLE35.5.1");
             end

rule "Step CLE35.5 - NO"
       when
             $step:Step(current.code=="CLE35.5"&&answer=="no");
       then
             $step.setNextQ("CLE36");
             end

rule "Step CLE35.5.1 - YES"
       when
             $step:Step(current.code=="CLE35.5.1"&&answer=="yes");
       then
             $step.setNextQ("CLE36");
             end

 rule "Step CLE35.5.1 - NO"
       when
             $step:Step(current.code=="CLE35.5.1"&&answer=="no");
       then
            $step.setTestFailed();
            end
 rule "Step CLE36 - YES"
       when
             $step:Step(current.code=="CLE36"&&answer=="yes");
       then
             $step.setNextQ("CLE37");
             end

 rule "Step CLE36 - NO"
       when
             $step:Step(current.code=="CLE36"&&answer=="no");
       then
             $step.setNextQ("CLE61");
             end

 rule "Step CLE37 - YES"
       when
             $step:Step(current.code=="CLE37"&&answer=="yes");
       then
            $step.setTestOK();
            end
 rule "Step CLE37 - NO"
       when
             $step:Step(current.code=="CLE37"&&answer=="no");
       then
             $step.setNextQ("CLE38");
             end


rule "Step CLE38 - YES"
       when
             $step:Step(current.code=="CLE38"&&answer=="yes");
       then
            $step.setTestOK();
            end
rule "Step CLE38 - NO"
       when
             $step:Step(current.code=="CLE38"&&answer=="no");
       then
             $step.setNextQ("CLE39");
             end


rule "Step CLE39 - YES"
       when
             $step:Step(current.code=="CLE39"&&answer=="yes");
       then
             $step.setNextQ("CLE40");
             end

rule "Step CLE39 - NO"
       when
             $step:Step(current.code=="CLE39"&&answer=="no");
       then
             $step.setNextQ("CLE46");
             end
rule "Step CLE40 - YES"
       when
             $step:Step(current.code=="CLE40"&&answer=="yes");
       then
             $step.setNextQ("CLE42");
             end

rule "Step CLE40 - NO"
       when
             $step:Step(current.code=="CLE40"&&answer=="no");
       then
             $step.setNextQ("CLE41");
             end
rule "Step CLE41 - YES"
       when
             $step:Step(current.code=="CLE41"&&answer=="yes");
       then
             $step.setNextQ("CLE46");
             end

rule "Step CLE41 - NO"
       when
             $step:Step(current.code=="CLE41"&&answer=="no");
       then
            $step.setTestFailed();
            end
rule "Step CLE42 - YES"
       when
             $step:Step(current.code=="CLE42"&&answer=="yes");
       then
            $step.setTestFailed();
            end
rule "Step CLE42 - NO"
       when
             $step:Step(current.code=="CLE42"&&answer=="no");
       then
             $step.setNextQ("CLE43");
             end

rule "Step CLE43 - YES"
       when
             $step:Step(current.code=="CLE43"&&answer=="yes");
       then
             $step.setNextQ("CLE44");
             end
 rule "Step CLE43 - NO"
       when
             $step:Step(current.code=="CLE43"&&answer=="no");
       then
            $step.setTestFailed();
            end
rule "Step CLE44 - YES"
       when
             $step:Step(current.code=="CLE44"&&answer=="yes");
       then
            $step.setTestFailed();
            end
 rule "Step CLE44 - NO"
       when
             $step:Step(current.code=="CLE44"&&answer=="no");
       then
             $step.setNextQ("CLE45");
             end

rule "Step CLE45 - YES"
       when
             $step:Step(current.code=="CLE45"&&answer=="yes");
       then
             $step.setNextQ("CLE46");
             end
rule "Step CLE45 - NO"
       when
             $step:Step(current.code=="CLE45"&&answer=="no");
       then
            $step.setTestFailed();
            end
rule "Step CLE46 - YES"
         when
               $step:Step(current.code=="CLE46"&&answer=="yes");
         then
               $step.setNextQ("CLE46.1.1");
               end

rule "Step CLE46 - NO(with component)"
          when
                $step:Step(current.code=="CLE46"&&answer=="no_not_only");
          then
                $step.setNextQ("CLE46.1.2");
                end

rule "Step CLE46 - NO(no component)"
            when
                  $step:Step(current.code=="CLE46"&&answer=="no_not_component");
            then
                  $step.setNextQ("CLE51");
                  end
rule "Step CLE46 - NO"
         when
               $step:Step(current.code=="CLE46"&&answer=="no");
         then
            $step.setTestOK();
            end



rule "Step CLE46.1.1 - YES"
         when
               $step:Step(current.code=="CLE46.1.1"&&answer=="yes");
         then
              $step.setTestOK();
              end
rule "Step CLE46.1.1 - NO"
         when
               $step:Step(current.code=="CLE46.1.1"&&answer=="no");
         then
               $step.setNextQ("CLE47.1");
               end



 rule "Step CLE47.1 - FIXED"
       when
            $step:Step(current.code=="CLE47.1"&&answer=="fixed");
       then
            $step.setNextQ("CLE49.1.1");
            end
rule "Step CLE47.1 - FLOAT"
       when
             $step:Step(current.code=="CLE47.1"&&answer=="floating");
       then
            $step.setNextQ("CLE48.1.1");
            end

rule "Step CLE48.1.1 - YES"
       when
            $step:Step(current.code=="CLE48.1.1"&&answer=="yes");
       then
            $step.setNextQ("CLE48.2.1");
            end
rule "Step CLE48.1.1 - NO"
       when
             $step:Step(current.code=="CLE48.1.1"&&answer=="no");
       then
              $step.setTestFailed();
              end
rule "Step CLE48.2.1 - YES"
       when
            $step:Step(current.code=="CLE48.2.1"&&answer=="yes");
       then
              $step.setTestFailed();
               end
rule "Step CLE48.2.1 - NO"
       when
             $step:Step(current.code=="CLE48.2.1"&&answer=="no");
       then
            $step.setNextQ("CLE48.3.1");
            end
rule "Step CLE48.3.1 - YES"
       when
            $step:Step(current.code=="CLE48.3.1"&&answer=="yes");
       then
              $step.setTestFailed();
               end
rule "Step CLE48.3.1 - NO"
       when
             $step:Step(current.code=="CLE48.3.1"&&answer=="no");
       then
            $step.setNextQ("CLE48.4.1");
            end

rule "Step CLE48.4.1 - YES"
       when
            $step:Step(current.code=="CLE48.4.1"&&answer=="yes");
       then
            $step.setNextQ("CLE48.5.1");
            end
rule "Step CLE48.4.1 - NO"
       when
             $step:Step(current.code=="CLE48.4.1"&&answer=="no");
       then
              $step.setNextQ("CLE48.7.1.1");
              end
rule "Step CLE48.5.1 - YES"
       when
            $step:Step(current.code=="CLE48.5.1"&&answer=="yes");
       then
            $step.setNextQ("CLE48.6.1");
            end
rule "Step CLE48.5.1 - NO"
       when
             $step:Step(current.code=="CLE48.5.1"&&answer=="no");
       then
            $step.setNextQ("CLE48.7.1.1");
            end
rule "Step CLE48.6.1 - YES"
       when
            $step:Step(current.code=="CLE48.6.1"&&answer=="yes");
       then
            $step.setNextQ("CLE48.7.1.1");
            end
rule "Step CLE48.6.1 - NO"
       when
             $step:Step(current.code=="CLE48.6.1"&&answer=="no");
       then
            $step.setNextQ("CLE49.1.1");
            end

rule "Step CLE48.7.1.1 - YES"
       when
            $step:Step(current.code=="CLE48.7.1.1"&&answer=="yes");
       then
            $step.setNextQ("CLE49.1.1");
            end
rule "Step CLE48.7.1.1 - NO"
       when
             $step:Step(current.code=="CLE48.7.1.1"&&answer=="no");
       then
            $step.setNextQ("CLE48.7.2.1");
            end

rule "Step CLE48.7.2.1 - YES"
       when
            $step:Step(current.code=="CLE48.7.2.1"&&answer=="yes");
       then
            $step.setTestFailed();
            end
rule "Step CLE48.7.2.1 - NO"
       when
             $step:Step(current.code=="CLE48.7.2.1"&&answer=="no");
       then
            $step.setNextQ("CLE49.1.1");
            end

rule "Step CLE49.1.1 - YES"
       when
            $step:Step(current.code=="CLE49.1.1"&&answer=="yes");
       then
            $step.setNextQ("CLE49.2.2.1");
            end
rule "Step CLE49.1.1 - NO(with_condition)"
       when
             $step:Step(current.code=="CLE49.1.1"&&answer=="no_with_condition");
       then
            $step.setNextQ("CLE49.2.1.1");
            end
rule "Step CLE49.1.1 - NO (not condition)"
       when
            $step:Step(current.code=="CLE49.1.1"&&answer=="no_not_condition");
       then
            $step.setTestOK();
           end
rule "Step CLE49.1.1 - NO(with_steps)"
       when
             $step:Step(current.code=="CLE49.1.1"&&answer=="no_with_step)");
       then
            $step.setNextQ("CLE50.1.1");
            end

rule "Step CLE49.2.1.1 - YES"
       when
             $step:Step(current.code=="CLE49.2.1.1"&&answer=="yes");
       then
            $step.setNextQ("CLE50.1.1");
            end

rule "Step CLE49.2.1.1 - NO"
       when
             $step:Step(current.code=="CLE49.2.1.1"&&answer=="no");
       then
            $step.setTestFailed();
            end
rule "Step CLE49.2.2.1 - YES"
       when
             $step:Step(current.code=="CLE49.2.2.1"&&answer=="yes");
       then
            $step.setTestOK();
            end
rule "Step CLE49.2.2.1 - NO"
       when
             $step:Step(current.code=="CLE49.2.2.1"&&answer=="no");
       then
            $step.setTestFailed();
            end

rule "Step CLE50.1.1 - YES"
       when
             $step:Step(current.code=="CLE50.1.1"&&answer=="yes");
       then
            $step.setNextQ("CLE50.2.1");
            end
rule "Step CLE50.1.1 - NO"
       when
             $step:Step(current.code=="CLE50.1.1"&&answer=="no");
       then
            $step.setNextQ("CLE50.2.1");
            end
rule "Step CLE50.2.1 - YES"
       when
             $step:Step(current.code=="CLE50.2.1"&&answer=="yes");
       then
            $step.setNextQ("CLE50.3.1");
            end
 rule "Step CLE50.2.1 - NO"
       when
             $step:Step(current.code=="CLE50.2.1"&&answer=="no");
       then
            $step.setNextQ("CLE50.3.1");
            end

 rule "Step CLE50.3.1 - YES"
       when
             $step:Step(current.code=="CLE50.3.1"&&answer=="yes");
       then
            $step.setNextQ("CLE50.3.1.1");
            end
 rule "Step CLE50.3.1 - NO"
       when
             $step:Step(current.code=="CLE50.3.1"&&answer=="no");
       then
            $step.setNextQ("CLE50.4.1");
            end

 rule "Step CLE50.3.1.1 - YES"
       when
             $step:Step(current.code=="CLE50.3.1.1"&&answer=="yes");
       then
            $step.setNextQ("CLE50.4.1");
            end
 rule "Step CLE50.3.1.1 - NO"
       when
             $step:Step(current.code=="CLE50.3.1.1"&&answer=="no");
       then
            $step.setNextQ("CLE50.3.2.1");
            end

rule "Step CLE50.3.2.1 - YES"
       when
             $step:Step(current.code=="CLE50.3.2.1"&&answer=="yes");
       then
            $step.setNextQ("CLE50.4.1");
            end
rule "Step CLE50.3.2.1 - NO"
       when
             $step:Step(current.code=="CLE50.3.2.1"&&answer=="no");
       then
            $step.setNextQ("CLE50.3.3.1");
            end

rule "Step CLE50.3.3.1 - YES"
       when
             $step:Step(current.code=="CLE50.3.3.1"&&answer=="yes");
       then
            $step.setNextQ("CLE50.4.1");
            end
rule "Step CLE50.3.3.1 - NO"
       when
             $step:Step(current.code=="CLE50.3.3.1"&&answer=="no");
       then
             $step.setTestFailed();
             end
rule "Step CLE50.4.1 - YES"
       when
             $step:Step(current.code=="CLE50.4.1"&&answer=="yes");
       then
             $step.setTestFailed();
            end

rule "Step CLE50.4.1 - NO"
       when
             $step:Step(current.code=="CLE50.4.1"&&answer=="no");
       then
            $step.setNextQ("CLE50.5.1");
            end

rule "Step CLE50.5.1 - YES"
       when
             $step:Step(current.code=="CLE50.5.1"&&answer=="yes");
       then
             $step.setTestFailed();
             end
rule "Step CLE50.5.1 - NO"
       when
             $step:Step(current.code=="CLE50.5.1"&&answer=="no");
       then
            $step.setNextQ("CLE50.6.1");
            end

 rule "Step CLE50.6.1 - YES"
       when
             $step:Step(current.code=="CLE50.6.1"&&answer=="yes");
       then
            $step.setNextQ("CLE50.6.1.1");
            end
 rule "Step CLE50.6.1 - NO"
       when
             $step:Step(current.code=="CLE50.6.1"&&answer=="no");
       then
            $step.setTestOK();
            end

 rule "Step CLE50.6.1.1 - YES"
       when
             $step:Step(current.code=="CLE50.6.1.1"&&answer=="yes");
       then
            $step.setTestOK();
            end
rule "Step CLE50.6.1.1 - NO"
       when
             $step:Step(current.code=="CLE50.6.1.1"&&answer=="no");
       then
             $step.setTestFailed();
             end

rule "Step CLE46.1.2 - YES"
         when
               $step:Step(current.code=="CLE46.1.2"&&answer=="yes");
         then
               $step.setNextQ("CLE51");
               end
rule "Step CLE46.1.2 - NO"
         when
               $step:Step(current.code=="CLE46.1.2"&&answer=="no");
         then
               $step.setNextQ("CLE47.2");
               end


//------

 rule "Step CLE47.2 - FIXED"
       when
            $step:Step(current.code=="CLE47.2"&&answer=="fixed");
       then
            $step.setNextQ("CLE49.1.2");
            end
rule "Step CLE47.2 - FLOAT"
       when
             $step:Step(current.code=="CLE47.2"&&answer=="floating");
       then
            $step.setNextQ("CLE48.1.2");
            end

rule "Step CLE48.1.2 - YES"
       when
            $step:Step(current.code=="CLE48.1.2"&&answer=="yes");
       then
            $step.setNextQ("CLE48.2.2");
            end
rule "Step CLE48.1.2 - NO"
       when
             $step:Step(current.code=="CLE48.1.2"&&answer=="no");
       then
              $step.setTestFailed();
              end
rule "Step CLE48.2.2 - YES"
       when
            $step:Step(current.code=="CLE48.2.2"&&answer=="yes");
       then
              $step.setTestFailed();
               end
rule "Step CLE48.2.2 - NO"
       when
             $step:Step(current.code=="CLE48.2.2"&&answer=="no");
       then
            $step.setNextQ("CLE48.3.2");
            end
rule "Step CLE48.3.2 - YES"
       when
            $step:Step(current.code=="CLE48.3.2"&&answer=="yes");
       then
              $step.setTestFailed();
               end
rule "Step CLE48.3.2 - NO"
       when
             $step:Step(current.code=="CLE48.3.2"&&answer=="no");
       then
            $step.setNextQ("CLE48.4.2");
            end

rule "Step CLE48.4.2 - YES"
       when
            $step:Step(current.code=="CLE48.4.2"&&answer=="yes");
       then
            $step.setNextQ("CLE48.5.2");
            end
rule "Step CLE48.4.2 - NO"
       when
             $step:Step(current.code=="CLE48.4.2"&&answer=="no");
       then
              $step.setNextQ("CLE48.7.1.2");
              end
rule "Step CLE48.5.2 - YES"
       when
            $step:Step(current.code=="CLE48.5.2"&&answer=="yes");
       then
            $step.setNextQ("CLE48.6.2");
            end
rule "Step CLE48.5.2 - NO"
       when
             $step:Step(current.code=="CLE48.5.2"&&answer=="no");
       then
            $step.setNextQ("CLE48.7.1.2");
            end
rule "Step CLE48.6.2 - YES"
       when
            $step:Step(current.code=="CLE48.6.2"&&answer=="yes");
       then
            $step.setNextQ("CLE48.7.1.2");
            end
rule "Step CLE48.6.2 - NO"
       when
             $step:Step(current.code=="CLE48.6.2"&&answer=="no");
       then
            $step.setNextQ("CLE49.1.2");
            end

rule "Step CLE48.7.1.2 - YES"
       when
            $step:Step(current.code=="CLE48.7.1.2"&&answer=="yes");
       then
            $step.setNextQ("CLE49.1.2");
            end
rule "Step CLE48.7.1.2 - NO"
       when
             $step:Step(current.code=="CLE48.7.1.2"&&answer=="no");
       then
            $step.setNextQ("CLE48.7.2.2");
            end

rule "Step CLE48.7.2.2 - YES"
       when
            $step:Step(current.code=="CLE48.7.2.2"&&answer=="yes");
       then
            $step.setTestFailed();
            end
rule "Step CLE48.7.2.2 - NO"
       when
             $step:Step(current.code=="CLE48.7.2.2"&&answer=="no");
       then
            $step.setNextQ("CLE49.1.2");
            end

rule "Step CLE49.1.2 - YES"
       when
            $step:Step(current.code=="CLE49.1.2"&&answer=="yes");
       then
            $step.setNextQ("CLE49.2.2.2");
            end
rule "Step CLE49.1.2 - NO(with_condition)"
       when
             $step:Step(current.code=="CLE49.1.2"&&answer=="no_with_condition");
       then
            $step.setNextQ("CLE49.2.1.2");
            end
rule "Step CLE49.1.2 - NO (not condition)"
       when
            $step:Step(current.code=="CLE49.1.2"&&answer=="no_not_condition");
       then
             $step.setNextQ("CLE51");
           end
rule "Step CLE49.1.2 - NO(with_steps)"
       when
             $step:Step(current.code=="CLE49.1.2"&&answer=="no_with_step");
       then
            $step.setNextQ("CLE50.1.2");
            end

rule "Step CLE49.2.1.2 - YES"
       when
             $step:Step(current.code=="CLE49.2.1.2"&&answer=="yes");
       then
            $step.setNextQ("CLE50.1.2");
            end

rule "Step CLE49.2.1.2 - NO"
       when
             $step:Step(current.code=="CLE49.2.1.2"&&answer=="no");
       then
            $step.setTestFailed();
            end
rule "Step CLE49.2.2.2 - YES"
       when
             $step:Step(current.code=="CLE49.2.2.2"&&answer=="yes");
       then
            $step.setNextQ("CLE51");
            end
rule "Step CLE49.2.2.2 - NO"
       when
             $step:Step(current.code=="CLE49.2.2.2"&&answer=="no");
       then
            $step.setTestFailed();
            end

rule "Step CLE50.1.2 - YES"
       when
             $step:Step(current.code=="CLE50.1.2"&&answer=="yes");
       then
            $step.setNextQ("CLE50.2.2");
            end
rule "Step CLE50.1.2 - NO"
       when
             $step:Step(current.code=="CLE50.1.2"&&answer=="no");
       then
            $step.setNextQ("CLE50.2.2");
            end
rule "Step CLE50.2.2 - YES"
       when
             $step:Step(current.code=="CLE50.2.2"&&answer=="yes");
       then
            $step.setNextQ("CLE50.3.2");
            end
 rule "Step CLE50.2.2 - NO"
       when
             $step:Step(current.code=="CLE50.2.2"&&answer=="no");
       then
            $step.setNextQ("CLE50.3.2");
            end

 rule "Step CLE50.3.2 - YES"
       when
             $step:Step(current.code=="CLE50.3.2"&&answer=="yes");
       then
            $step.setNextQ("CLE50.3.1.2");
            end
 rule "Step CLE50.3.2 - NO"
       when
             $step:Step(current.code=="CLE50.3.2"&&answer=="no");
       then
            $step.setNextQ("CLE50.4.2");
            end

 rule "Step CLE50.3.1.2 - YES"
       when
             $step:Step(current.code=="CLE50.3.1.2"&&answer=="yes");
       then
            $step.setNextQ("CLE50.4.2");
            end
 rule "Step CLE50.3.1.2 - NO"
       when
             $step:Step(current.code=="CLE50.3.1.2"&&answer=="no");
       then
            $step.setNextQ("CLE50.3.2.2");
            end

rule "Step CLE50.3.2.2 - YES"
       when
             $step:Step(current.code=="CLE50.3.2.2"&&answer=="yes");
       then
            $step.setNextQ("CLE50.4.2");
            end
rule "Step CLE50.3.2.2 - NO"
       when
             $step:Step(current.code=="CLE50.3.2.2"&&answer=="no");
       then
            $step.setNextQ("CLE50.3.3.2");
            end

rule "Step CLE50.3.3.2 - YES"
       when
             $step:Step(current.code=="CLE50.3.3.2"&&answer=="yes");
       then
            $step.setNextQ("CLE50.4.2");
            end
rule "Step CLE50.3.3.2 - NO"
       when
             $step:Step(current.code=="CLE50.3.3.2"&&answer=="no");
       then
             $step.setTestFailed();
             end
rule "Step CLE50.4.2 - YES"
       when
             $step:Step(current.code=="CLE50.4.2"&&answer=="yes");
       then
             $step.setTestFailed();
            end

rule "Step CLE50.4.2 - NO"
       when
             $step:Step(current.code=="CLE50.4.2"&&answer=="no");
       then
            $step.setNextQ("CLE50.5.2");
            end

rule "Step CLE50.5.2 - YES"
       when
             $step:Step(current.code=="CLE50.5.2"&&answer=="yes");
       then
             $step.setTestFailed();
             end
rule "Step CLE50.5.2 - NO"
       when
             $step:Step(current.code=="CLE50.5.2"&&answer=="no");
       then
            $step.setNextQ("CLE50.6.2");
            end

rule "Step CLE50.6.2 - YES"
       when
             $step:Step(current.code=="CLE50.6.2"&&answer=="yes");
       then
            $step.setNextQ("CLE50.6.1.2");
            end
rule "Step CLE50.6.2 - NO"
       when
             $step:Step(current.code=="CLE50.6.2"&&answer=="no");
       then
            $step.setNextQ("CLE51");
            end

rule "Step CLE50.6.1.2 - YES"
       when
             $step:Step(current.code=="CLE50.6.1.2"&&answer=="yes");
       then
            $step.setNextQ("CLE51");
            end
rule "Step CLE50.6.1.2 - NO"
       when
             $step:Step(current.code=="CLE50.6.1.2"&&answer=="no");
       then
             $step.setTestFailed();
             end
//-------





rule "Step CLE51 - YES"
          when
                $step:Step(current.code=="CLE51"&&answer=="yes");
          then
                $step.setNextQ("CLE52");
                end
rule "Step CLE51 - NO"
          when
                $step:Step(current.code=="CLE51"&&answer=="no");
          then
                $step.setNextQ("CLE57");
                end

rule "Step CLE52 - YES"
          when
                $step:Step(current.code=="CLE52"&&answer=="yes");
          then
                $step.setNextQ("CLE53");
                end
rule "Step CLE52 - NO"
          when
                $step:Step(current.code=="CLE52"&&answer=="no");
          then
              $step.setTestFailed();
           end

rule "Step CLE53 - FIXED"
      when
           $step:Step(current.code=="CLE53"&&answer=="fixed");
      then
           $step.setNextQ("CLE55.1");
           end
rule "Step CLE53 - FLOAT"
      when
            $step:Step(current.code=="CLE53"&&answer=="floating");
      then
           $step.setNextQ("CLE54.1");
           end

rule "Step CLE54.1 - YES"
      when
           $step:Step(current.code=="CLE54.1"&&answer=="yes");
      then
           $step.setNextQ("CLE54.2");
           end
rule "Step CLE54.1 - NO"
      when
            $step:Step(current.code=="CLE54.1"&&answer=="no");
      then
             $step.setTestFailed();
             end
rule "Step CLE54.2 - YES"
      when
           $step:Step(current.code=="CLE54"&&answer=="yes");
      then
             $step.setTestFailed();
            end
rule "Step CLE54.2 - NO"
      when
            $step:Step(current.code=="CLE54.2"&&answer=="no");
      then
           $step.setNextQ("CLE54.3");
           end
rule "Step CLE54.3 - YES"
      when
           $step:Step(current.code=="CLE54.3"&&answer=="yes");
      then
             $step.setTestFailed();
             end
rule "Step CLE54.3 - NO"
      when
            $step:Step(current.code=="CLE54.3"&&answer=="no");
      then
           $step.setNextQ("CLE54.4");
           end

rule "Step CLE54.4 - YES"
      when
           $step:Step(current.code=="CLE54.4"&&answer=="yes");
      then
           $step.setNextQ("CLE54.5");
           end
rule "Step CLE54.4 - NO"
      when
            $step:Step(current.code=="CLE54.4"&&answer=="no");
      then
             $step.setNextQ("CLE54.7.1");
             end
rule "Step CLE54.5 - YES"
      when
           $step:Step(current.code=="CLE54.5"&&answer=="yes");
      then
           $step.setNextQ("CLE54.6");
           end
rule "Step CLE54.5 - NO"
      when
            $step:Step(current.code=="CLE54.5"&&answer=="no");
      then
           $step.setNextQ("CLE54.7.1");
           end
rule "Step CLE54.6 - YES"
      when
           $step:Step(current.code=="CLE54.6"&&answer=="yes");
      then
           $step.setNextQ("CLE54.7.1");
           end
rule "Step CLE54.6 - NO"
      when
            $step:Step(current.code=="CLE54.6"&&answer=="no");
      then
           $step.setNextQ("CLE55.1");
           end

rule "Step CLE54.7.1 - YES"
      when
           $step:Step(current.code=="CLE54.7.1"&&answer=="yes");
      then
           $step.setNextQ("CLE55.1");
           end
rule "Step CLE54.7.1 - NO"
      when
            $step:Step(current.code=="CLE54.7.1"&&answer=="no");
      then
           $step.setNextQ("CLE54.7.2");
           end

rule "Step CLE54.7.2 - YES"
      when
           $step:Step(current.code=="CLE54.7.1"&&answer=="yes");
      then
           $step.setTestFailed();
           end
rule "Step CLE54.7.2 - NO"
      when
            $step:Step(current.code=="CLE54.7.1"&&answer=="no");
      then
           $step.setNextQ("CLE55.1");
           end

rule "Step CLE55.1 - YES"
      when
           $step:Step(current.code=="CLE55.1"&&answer=="yes");
      then
           $step.setNextQ("CLE55.2.2");
           end
rule "Step CLE55.1 - NO(with_condition)"
      when
            $step:Step(current.code=="CLE55.1"&&answer=="no_with_condition");
      then
           $step.setNextQ("CLE55.2.1");
           end
rule "Step CLE55.1 - NO (not condition)"
      when
           $step:Step(current.code=="CLE55.1"&&answer=="no_not_condition");
      then
           $step.setNextQ("CLE57");
           end
rule "Step CLE55.1 - NO(with_steps)"
      when
            $step:Step(current.code=="CLE55.1"&&answer=="no_with_step");
      then
           $step.setNextQ("CLE56.1");
           end

rule "Step CLE55.2.1 - YES"
      when
            $step:Step(current.code=="CLE55.2.1"&&answer=="yes");
      then
           $step.setNextQ("CLE56.1");
           end

rule "Step CLE55.2.1 - NO"
      when
            $step:Step(current.code=="CLE55.2.1"&&answer=="no");
      then
           $step.setTestFailed();
           end
rule "Step CLE55.2.2 - YES"
      when
            $step:Step(current.code=="CLE55.2.2"&&answer=="yes");
      then
           $step.setNextQ("CLE57");
           end

rule "Step CLE55.2.2 - NO"
      when
            $step:Step(current.code=="CLE55.2.2"&&answer=="no");
      then
           $step.setTestFailed();
           end

rule "Step CLE56.1 - YES"
      when
            $step:Step(current.code=="CLE56.1"&&answer=="yes");
      then
           $step.setNextQ("CLE56.2");
           end
rule "Step CLE56.1 - NO"
      when
            $step:Step(current.code=="CLE56.1"&&answer=="no");
      then
           $step.setNextQ("CLE56.2");
           end
rule "Step CLE56.2 - YES"
      when
            $step:Step(current.code=="CLE56.2"&&answer=="yes");
      then
           $step.setNextQ("CLE56.3");
           end
rule "Step CLE56.2 - NO"
      when
            $step:Step(current.code=="CLE56.2"&&answer=="no");
      then
           $step.setNextQ("CLE56.3");
           end

rule "Step CLE56.3 - YES"
      when
            $step:Step(current.code=="CLE56.3"&&answer=="yes");
      then
           $step.setNextQ("CLE56.3.1");
           end
rule "Step CLE56.3 - NO"
      when
            $step:Step(current.code=="CLE56.3"&&answer=="no");
      then
           $step.setNextQ("CLE56.4");
           end

rule "Step CLE56.3.1 - YES"
      when
            $step:Step(current.code=="CLE56.3.1"&&answer=="yes");
      then
           $step.setNextQ("CLE56.4");
           end
rule "Step CLE56.3.1 - NO"
      when
            $step:Step(current.code=="CLE56.3.1"&&answer=="no");
      then
           $step.setNextQ("CLE56.3.2");
           end

rule "Step CLE56.3.2 - YES"
      when
            $step:Step(current.code=="CLE56.3.2"&&answer=="yes");
      then
           $step.setNextQ("CLE56.4");
           end
rule "Step CLE56.3.2 - NO"
      when
            $step:Step(current.code=="CLE56.3.2"&&answer=="no");
      then
           $step.setNextQ("CLE56.3.3");
           end

rule "Step CLE56.3.3 - YES"
      when
            $step:Step(current.code=="CLE56.3.3"&&answer=="yes");
      then
           $step.setNextQ("CLE56.4");
           end
rule "Step CLE56.3.3 - NO"
      when
            $step:Step(current.code=="CLE56.3.3"&&answer=="no");
      then
           $step.setTestFailed();
           
end
rule "Step CLE56.4 - YES"
      when
            $step:Step(current.code=="CLE56.4"&&answer=="yes");
      then
           $step.setTestFailed();
           
end
rule "Step CLE56.4 - NO"
      when
            $step:Step(current.code=="CLE56.4"&&answer=="no");
      then
           $step.setNextQ("CLE56.5");
           end

rule "Step CLE56.5 - YES"
      when
            $step:Step(current.code=="CLE56.5"&&answer=="yes");
      then
            $step.setTestFailed();
           end
rule "Step CLE56.5 - NO"
      when
            $step:Step(current.code=="CLE56.5"&&answer=="no");
      then
           $step.setNextQ("CLE56.6");
           end

rule "Step CLE56.6 - YES"
      when
            $step:Step(current.code=="CLE56.6"&&answer=="yes");
      then
           $step.setNextQ("CLE56.6.1");
           end
rule "Step CLE56.6 - NO"
      when
            $step:Step(current.code=="CLE56.6"&&answer=="no");
      then
           $step.setNextQ("CLE57");
           end

rule "Step CLE56.6.1 - YES"
      when
            $step:Step(current.code=="CLE56.6.1"&&answer=="yes");
      then
           $step.setNextQ("CLE57");
           end
rule "Step CLE56.6.1 - NO"
      when
            $step:Step(current.code=="CLE56.6.1"&&answer=="no");
      then
            $step.setTestFailed();
           end

rule "Step CLE57 - YES"
          when
                $step:Step(current.code=="CLE57"&&answer=="yes");
          then
                $step.setNextQ("CLE58");
                end
rule "Step CLE57 - NO"
          when
                $step:Step(current.code=="CLE57"&&answer=="no");
          then
                $step.setNextQ("CLE58");
                end

rule "Step CLE58 - YES"
          when
                $step:Step(current.code=="CLE58"&&answer=="yes");
          then
                $step.setNextQ("CLE59");
                end
rule "Step CLE58 - NO(amount update)"
          when
                $step:Step(current.code=="CLE58"&&answer=="no_amount_update");
          then
              $step.setTestFailed();
             end
rule "Step CLE58 - NO(no component)"
          when
                $step:Step(current.code=="CLE58"&&answer=="not_component");
          then
                $step.setNextQ("CLE59");
                end

rule "Step CLE59 - YES"
          when
                $step:Step(current.code=="CLE59"&&answer=="yes");
          then
              $step.setTestFailed();
              end
rule "Step CLE59 - NO"
          when
                $step:Step(current.code=="CLE59"&&answer=="no");
          then
                $step.setNextQ("CLE60");
                end
rule "Step CLE60 - YES"
          when
                $step:Step(current.code=="CLE60"&&answer=="yes");
          then
                $step.setNextQ("CLE60.1");
                end
rule "Step CLE60 - NO"
          when
                $step:Step(current.code=="CLE60"&&answer=="no");
          then
              $step.setTestOK();
              end

rule "Step CLE60.1 - YES"
          when
                $step:Step(current.code=="CLE60"&&answer=="no");
          then
              $step.setTestOK();
             end
rule "Step CLE60.1 - NO"
          when
                $step:Step(current.code=="CLE60.1"&&answer=="no");
          then
             $step.setTestFailed();
           end
rule "Step CLE61 - YES"
          when
                $step:Step(current.code=="CLE61"&&answer=="yes");
          then
            $step.setNextQ("CLE62");
            end
rule "Step CLE61 - NO"
          when
                $step:Step(current.code=="CLE61"&&answer=="no");
          then
           $step.setTestOK();
           end
rule "Step CLE62 - YES"
          when
                $step:Step(current.code=="CLE62"&&answer=="yes");
          then
              $step.setTestFailed();
           end
rule "Step CLE62 - NO"
          when
                $step:Step(current.code=="CLE62"&&answer=="no");
          then
              $step.setTestOK();
           end

