import com.egartech.sppi.model.Step;
import com.egartech.sppi.model.Product;

rule "define first question of GZ test"
    when
        $product:Product(productCode=="gray_zone");
    then
        $product.setFirstQuestionCode("GZ1");
end

rule "Step 1 - YES"
    when
        $step:Step(current.code=="GZ1"&&answer=="yes");
    then
        $step.setNextQ("GZ2");
        
end

rule "Step 1 - NO"
    when
        $step:Step(current.code=="GZ1"&&answer=="no");
    then
        $step.setNextQ("GZ3");
        
end

rule "Step 2 - YES"
    when
        $step:Step(current.code=="GZ2"&&answer=="yes");
    then
        $step.setTestFailed();
        
end
rule "Step 2 - NO"
     when
         $step:Step(current.code=="GZ2"&&answer=="no");
     then
         $step.setNextQ("GZ3");
         
end
rule "Step 3 - YES"
     when
         $step:Step(current.code=="GZ3"&&answer=="yes");
     then
        $step.setNextQ("GZ4");
         
end
rule "Step 3 - NO"
     when
         $step:Step(current.code=="GZ3"&&answer=="no");
     then
        $step.setTestOK();
        
end
rule "Step 4 - YES"
     when
         $step:Step(current.code=="GZ4"&&answer=="yes");
     then
        $step.setNextQ("GZ5");
         
end
rule "Step 4 - NO"
     when
         $step:Step(current.code=="GZ4"&&answer=="no");
     then
        $step.setTestOK();
        
end
rule "Step 5 - YES"
     when
         $step:Step(current.code=="GZ5"&&answer=="yes");
     then
        $step.setTestOK();
         
end
rule "Step 5 - NO"
     when
         $step:Step(current.code=="GZ5"&&answer=="no");
     then
        $step.setTestFailed();
end