import com.egartech.sppi.model.Step;
import com.egartech.sppi.model.Product;

rule "define first question of CB test"
    when
        $product:Product(productCode=="securities");
    then
        $product.setFirstQuestionCode("CB1");
end

rule "Step CB1 - YES"
    when
        $step:Step(current.code=="CB1"&&answer=="yes");
    then
        $step.setNextQ("CB2");
        
end
rule "Step CB1 - NO"
    when
        $step:Step(current.code=="CB1"&&answer=="no");
    then
        $step.setNextQ("CB6");
        end

rule "Step CB2 - YES-Only CLI"
    when
        $step:Step(current.code=="CB2"&&answer=="yes_only_cli");
    then
        $step.setNextQ("CB3.1.2");
        end
rule "Step CB2 - NO-not only CLI"
    when
        $step:Step(current.code=="CB2"&&answer=="no_not_only_cli");
    then
        $step.setNextQ("CB3.1.1");
        end
rule "Step CB2 - NO"
     when
         $step:Step(current.code=="CB2"&&answer=="no_not_cli");
     then
         $step.setNextQ("CB4");
         end
rule "Step CB3.1.2 - YES"
     when
         $step:Step(current.code=="CB3.1.2"&&answer=="yes");
     then
        $step.setTestFailed();
        end
rule "Step CB3.1.2 - NO"
     when
         $step:Step(current.code=="CB3.1.2"&&answer=="no");
     then
         $step.setNextQ("CB3.2.2");
         end
rule "Step CB3.2.2 - YES"
     when
         $step:Step(current.code=="CB3.2.2"&&answer=="yes");
     then
         $step.setNextQ("CB3.3.2");
         end
rule "Step CB3.2.2 - NO"
     when
         $step:Step(current.code=="CB3.2.2"&&answer=="no");
     then
         $step.setTestFailed();
         end
rule "Step CB3.3.2 - YES"
     when
         $step:Step(current.code=="CB3.3.2"&&answer=="yes");
     then
         $step.setNextQ("CB3.4.2");
         end
rule "Step CB3.3.2 - NO"
     when
         $step:Step(current.code=="CB3.3.2"&&answer=="no");
     then
         $step.setTestFailed();
         end
rule "Step CB3.4.2 - YES"
     when
         $step:Step(current.code=="CB3.4.2"&&answer=="yes");
     then
         $step.setTestFailed();
         end
rule "Step CB3.4.2 - NO"
     when
         $step:Step(current.code=="CB3.4.2"&&answer=="no");
     then
         $step.setNextQ("CB3.5.2");
         end

rule "Step CB3.5.2 - YES"
     when
         $step:Step(current.code=="CB3.5.2"&&answer=="yes");
     then
        $step.setNextQ("CB6");
        end
rule "Step CB3.5.2 - NO"
     when
         $step:Step(current.code=="CB3.5.2"&&answer=="no");
     then
         $step.setNextQ("CB3.6.2");
         end

 rule "Step CB3.6.2 - YES"
      when
          $step:Step(current.code=="CB3.6.2"&&answer=="yes");
      then
         $step.setNextQ("CB6");
         end
 rule "Step CB3.6.2 - NO"
      when
          $step:Step(current.code=="CB3.6.2"&&answer=="no");
      then
         $step.setTestFailed();
         end

rule "Step CB3.1.1 - YES"
     when
         $step:Step(current.code=="CB3.1.1"&&answer=="yes");
     then
        $step.setTestFailed();
        end
rule "Step CB3.1.1 - NO"
     when
         $step:Step(current.code=="CB3.1.1"&&answer=="no");
     then
         $step.setNextQ("CB3.2.1");
         end
rule "Step CB3.2.1 - YES"
     when
         $step:Step(current.code=="CB3.2.1"&&answer=="yes");
     then
         $step.setNextQ("CB3.3.1");
         end
rule "Step CB3.2.1 - NO"
     when
         $step:Step(current.code=="CB3.2.1"&&answer=="no");
     then
         $step.setTestFailed();
         end
rule "Step CB3.3.1 - YES"
     when
         $step:Step(current.code=="CB3.3.1"&&answer=="yes");
     then
         $step.setNextQ("CB3.4.1");
         end
rule "Step CB3.3.1 - NO"
     when
         $step:Step(current.code=="CB3.3.1"&&answer=="no");
     then
         $step.setTestFailed();
         end
rule "Step CB3.4.1 - YES"
     when
         $step:Step(current.code=="CB3.4.1"&&answer=="yes");
     then
         $step.setTestFailed();
         end
rule "Step CB3.4.1 - NO"
     when
         $step:Step(current.code=="CB3.4.1"&&answer=="no");
     then
         $step.setNextQ("CB3.5.1");
         end

rule "Step CB3.5.1 - YES"
     when
         $step:Step(current.code=="CB3.5.1"&&answer=="yes");
     then
        $step.setNextQ("CB4");
        end
rule "Step CB3.5.1 - NO"
     when
         $step:Step(current.code=="CB3.5.1"&&answer=="no");
     then
         $step.setNextQ("CB3.6.1");
         end

rule "Step CB3.6.1 - YES"
      when
          $step:Step(current.code=="CB3.6.1"&&answer=="yes");
      then
         $step.setNextQ("CB4");
         end
rule "Step CB3.6.1 - NO"
      when
          $step:Step(current.code=="CB3.6.1"&&answer=="no");
      then
         $step.setTestFailed();
         end

rule "Step CB4 - YES"
      when
           $step:Step(current.code=="CB4"&&answer=="yes");
      then
           $step.setNextQ("CB6");
           end
rule "Step CB4 - NO"
      when
            $step:Step(current.code=="CB4"&&answer=="no");
      then
           $step.setNextQ("CB5");
           end

rule "Step CB5 - YES"
      when
           $step:Step(current.code=="CB5"&&answer=="yes");
      then
           $step.setNextQ("CB6");
           end
rule "Step CB5 - NO"
        when
            $step:Step(current.code=="CB5"&&answer=="no");
        then
             $step.setTestFailed();
             end

rule "Step CB6 - FIXED"
      when
           $step:Step(current.code=="CB6"&&answer=="fixed");
      then
           $step.setNextQ("CB8.1");
           end
rule "Step CB6 - FLOAT"
      when
            $step:Step(current.code=="CB6"&&answer=="floating");
      then
           $step.setNextQ("CB7.1");
           end

rule "Step CB7.1 - YES"
      when
           $step:Step(current.code=="CB7.1"&&answer=="yes");
      then
           $step.setNextQ("CB7.2");
           end
rule "Step CB7.1 - NO"
      when
            $step:Step(current.code=="CB7.1"&&answer=="no");
      then
             $step.setTestFailed();
             end

rule "Step CB7.2 - YES"
      when
           $step:Step(current.code=="CB7.2"&&answer=="yes");
      then
             $step.setTestFailed();
             end
rule "Step CB7.2 - NO"
      when
            $step:Step(current.code=="CB7.2"&&answer=="no");
      then
           $step.setNextQ("CB7.3");
           end
rule "Step CB7.3 - YES"
      when
           $step:Step(current.code=="CB7.3"&&answer=="yes");
      then
             $step.setTestFailed();
             end
rule "Step CB7.3 - NO"
      when
            $step:Step(current.code=="CB7.3"&&answer=="no");
      then
           $step.setNextQ("CB7.4");
           end

rule "Step CB7.4 - YES"
      when
           $step:Step(current.code=="CB7.4"&&answer=="yes");
      then
           $step.setNextQ("CB7.5");
           end
rule "Step CB7.4 - NO"
      when
            $step:Step(current.code=="CB7.4"&&answer=="no");
      then
             $step.setNextQ("CB7.7.1");
             end
rule "Step CB7.5 - YES"
      when
           $step:Step(current.code=="CB7.5"&&answer=="yes");
      then
           $step.setNextQ("CB7.6");
           end
rule "Step CB7.5 - NO"
      when
            $step:Step(current.code=="CB7.5"&&answer=="no");
      then
           $step.setNextQ("CB7.7.1");
           end
rule "Step CB7.6 - YES"
      when
           $step:Step(current.code=="CB7.6"&&answer=="yes");
      then
           $step.setNextQ("CB7.7.1");
           end
rule "Step CB7.6 - NO"
      when
            $step:Step(current.code=="CB7.6"&&answer=="no");
      then
           $step.setNextQ("CB8.1");
           end

rule "Step CB7.7.1 - YES"
      when
           $step:Step(current.code=="CB7.7.1"&&answer=="yes");
      then
           $step.setNextQ("CB8.1");
           end
rule "Step CB7.7.1 - NO"
      when
            $step:Step(current.code=="CB7.7.1"&&answer=="no");
      then
           $step.setNextQ("CB7.7.2");
           end

rule "Step CB7.7.2 - YES"
      when
           $step:Step(current.code=="CB7.7.2"&&answer=="yes");
      then
           $step.setTestFailed();
           end
rule "Step CB7.7.2 - NO"
      when
            $step:Step(current.code=="CB7.7.2"&&answer=="no");
      then
           $step.setNextQ("CB8.1");
           end

rule "Step CB8.1 - YES"
      when
           $step:Step(current.code=="CB8.1"&&answer=="yes");
      then
           $step.setNextQ("CB8.2.2");
           end
rule "Step CB8.1 - NO(with_condition)"
      when
            $step:Step(current.code=="CB8.1"&&answer=="no_with_condition");
      then
           $step.setNextQ("CB8.2.1");
           end
rule "Step CB8.1 - NO (with step)"
      when
           $step:Step(current.code=="CB8.1"&&answer=="no_with_step");
      then
           $step.setNextQ("CB9.1");
           end
rule "Step CB8.1 - NO(not_condition)"
      when
            $step:Step(current.code=="CB8.1"&&answer=="no_not_condition");
      then
           $step.setNextQ("CB10");
           end

rule "Step CB8.2.1 - YES"
      when
            $step:Step(current.code=="CB8.2.1"&&answer=="yes");
      then
           $step.setNextQ("CB9.1");
           end

rule "Step CB8.2.1 - NO"
      when
            $step:Step(current.code=="CB8.2.1"&&answer=="no");
      then
           $step.setTestFailed();
           end
rule "Step CB8.2.2 - YES"
      when
            $step:Step(current.code=="CB8.2.2"&&answer=="yes");
      then
           $step.setNextQ("CB10");
           end

rule "Step CB8.2.2 - NO"
      when
            $step:Step(current.code=="CB8.2.1"&&answer=="no");
      then
           $step.setTestFailed();
           end

rule "Step CB9.1 - YES"
      when
            $step:Step(current.code=="CB9.1"&&answer=="yes");
      then
           $step.setNextQ("CB9.2");
           end
rule "Step CB9.1 - NO"
      when
            $step:Step(current.code=="CB9.1"&&answer=="no");
      then
           $step.setNextQ("CB9.2");
           end
rule "Step CB9.2 - YES"
      when
            $step:Step(current.code=="CB9.2"&&answer=="yes");
      then
           $step.setNextQ("CB9.3");
           end
rule "Step CB9.2 - NO"
      when
            $step:Step(current.code=="CB9.2"&&answer=="no");
      then
           $step.setNextQ("CB9.3");
           end

rule "Step CB9.3 - YES"
      when
            $step:Step(current.code=="CB9.3"&&answer=="yes");
      then
           $step.setTestFailed();
           end
rule "Step CB9.3 - NO"
      when
            $step:Step(current.code=="CB9.3"&&answer=="no");
      then
           $step.setNextQ("CB9.4");
           end

rule "Step CB9.4 - YES"
      when
            $step:Step(current.code=="CB9.4"&&answer=="yes");
      then
            $step.setTestFailed();
            end
rule "Step CB9.4 - NO"
      when
            $step:Step(current.code=="CB9.4"&&answer=="no");
      then
           $step.setNextQ("CB9.5");
           end

rule "Step CB9.5 - YES"
      when
            $step:Step(current.code=="CB9.5"&&answer=="yes");
      then
           $step.setNextQ("CB9.5.1");
           end
rule "Step CB9.5 - NO"
      when
            $step:Step(current.code=="CB9.5"&&answer=="no");
      then
           $step.setNextQ("CB10");
           end

rule "Step CB9.5.1 - YES"
      when
            $step:Step(current.code=="CB9.5.1"&&answer=="yes");
      then
           $step.setNextQ("CB10");
           end
rule "Step CB9.5.1 - NO"
      when
            $step:Step(current.code=="CB9.5.1"&&answer=="no");
      then
           $step.setTestFailed();
           end


rule "Step CB10 - YES"
      when
            $step:Step(current.code=="CB10"&&answer=="yes");
      then
           $step.setNextQ("CB11");
           end
rule "Step CB10 - NO"
      when
            $step:Step(current.code=="CB10"&&answer=="no");
      then
           $step.setNextQ("CB15");
           end

rule "Step CB11 - YES"
      when
            $step:Step(current.code=="CB11"&&answer=="yes");
      then
           $step.setNextQ("CB14.1");
           end
rule "Step CB11 - NO"
      when
            $step:Step(current.code=="CB11"&&answer=="no");
      then
           $step.setNextQ("CB12");
           end

rule "Step CB12 - YES"
      when
            $step:Step(current.code=="CB12"&&answer=="yes");
      then
           $step.setNextQ("CB15");
           end
rule "Step CB12 - NO"
      when
            $step:Step(current.code=="CB12"&&answer=="no");
      then
           $step.setNextQ("CB13.1");
           end

rule "Step CB13.1 - YES"
      when
            $step:Step(current.code=="CB13.1"&&answer=="yes");
      then
           $step.setNextQ("CB13.2");
           end
rule "Step CB13.1 - NO"
      when
            $step:Step(current.code=="CB13.1"&&answer=="no");
      then
           $step.setNextQ("CB13.2");
           end

rule "Step CB13.2 - YES"
      when
            $step:Step(current.code=="CB13.2"&&answer=="yes");
      then
           $step.setNextQ("CB13.3");
           end
rule "Step CB13.2 - NO"
      when
            $step:Step(current.code=="CB13.2"&&answer=="no");
      then
           $step.setNextQ("CB13.3");
           end

rule "Step CB13.3 - YES"
      when
            $step:Step(current.code=="CB13.3"&&answer=="yes");
      then
           $step.setNextQ("CB13.4");
           end
rule "Step CB13.3 - NO"
      when
            $step:Step(current.code=="CB13.3"&&answer=="no");
      then
           $step.setNextQ("CB13.4");
           end

rule "Step CB13.4 - YES"
      when
            $step:Step(current.code=="CB13.4"&&answer=="yes");
      then
            $step.setTestFailed();
            end
rule "Step CB13.4 - NO"
      when
            $step:Step(current.code=="CB13.4"&&answer=="no");
      then
           $step.setNextQ("CB13.5");
           end
rule "Step CB13.5 - YES"
      when
            $step:Step(current.code=="CB13.5"&&answer=="yes");
      then
            $step.setTestFailed();
            end
rule "Step CB13.5 - NO"
      when
            $step:Step(current.code=="CB13.5"&&answer=="no");
      then
           $step.setNextQ("CB13.6");
           end
rule "Step CB13.6 - YES"
      when
            $step:Step(current.code=="CB13.6"&&answer=="yes");
      then
           $step.setNextQ("CB13.6.1");
           end
rule "Step CB13.6 - NO"
      when
            $step:Step(current.code=="CB13.6"&&answer=="no");
      then
           $step.setNextQ("CB15");
           end
rule "Step CB13.6.1 - YES"
      when
            $step:Step(current.code=="CB13.6.1"&&answer=="yes");
      then
           $step.setNextQ("CB15");
           end
rule "Step CB13.6.1 - NO"
      when
            $step:Step(current.code=="CB13.6.1"&&answer=="no");
      then
           $step.setTestFailed();
           end

rule "Step CB14.1 - YES"
      when
            $step:Step(current.code=="CB14.1"&&answer=="yes");
      then
           $step.setNextQ("CB14.2");
           end
rule "Step CB14.1 - NO"
      when
            $step:Step(current.code=="CB14.1"&&answer=="no");
      then
           $step.setNextQ("CB12");
           end

rule "Step CB14.2 - YES"
      when
            $step:Step(current.code=="CB14.2"&&answer=="yes");
      then
           $step.setNextQ("CB12");
           end
rule "Step CB14.2 - NO"
      when
            $step:Step(current.code=="CB14.2"&&answer=="no");
      then
           $step.setTestFailed();
           end

rule "Step CB15 - YES"
      when
            $step:Step(current.code=="CB15"&&answer=="yes");
      then
           $step.setNextQ("CB16");
           end
rule "Step CB15 - NO"
      when
            $step:Step(current.code=="CB15"&&answer=="no");
      then
           $step.setNextQ("CB24");
           end

rule "Step CB16 - YES"
      when
            $step:Step(current.code=="CB16"&&answer=="yes");
      then
           $step.setNextQ("CB24");
           end
rule "Step CB16 - NO"
      when
            $step:Step(current.code=="CB16"&&answer=="no");
      then
           $step.setNextQ("CB17");
           end

rule "Step CB17 - YES"
      when
            $step:Step(current.code=="CB17"&&answer=="yes");
      then
           $step.setNextQ("CB24");
           end
rule "Step CB17 - NO"
      when
            $step:Step(current.code=="CB17"&&answer=="no");
      then
           $step.setNextQ("CB18");
           end


rule "Step CB18 - FIXED"
      when
           $step:Step(current.code=="CB18"&&answer=="fixed");
      then
           $step.setNextQ("CB20.1");
           end
rule "Step CB18.6 - FLOAT"
      when
            $step:Step(current.code=="CB18"&&answer=="floating");
      then
           $step.setNextQ("CB19.1");
           end

rule "Step CB19.1 - YES"
      when
           $step:Step(current.code=="CB19.1"&&answer=="yes");
      then
           $step.setNextQ("CB19.2");
           end
rule "Step CB19.1 - NO"
      when
            $step:Step(current.code=="CB18.7.1"&&answer=="no");
      then
           $step.setTestFailed();
           end
rule "Step CB19.2 - YES"
      when
           $step:Step(current.code=="CB19.2"&&answer=="yes");
      then
             $step.setTestFailed();
             end
rule "Step CB19.2 - NO"
      when
            $step:Step(current.code=="CB19.2"&&answer=="no");
      then
           $step.setNextQ("CB19.3");
           end
rule "Step CB19.3 - YES"
      when
           $step:Step(current.code=="CB19.3"&&answer=="yes");
      then
           $step.setTestFailed();
           end
rule "Step CB19.3 - NO"
      when
            $step:Step(current.code=="CB19.3"&&answer=="no");
      then
           $step.setNextQ("CB19.4");
           end

rule "Step CB19.4 - YES"
      when
           $step:Step(current.code=="CB19.4"&&answer=="yes");
      then
           $step.setNextQ("CB19.5");
           end
rule "Step CB19.4 - NO"
      when
            $step:Step(current.code=="CB19.4"&&answer=="no");
      then
             $step.setNextQ("CB19.7.1");
             end
rule "Step CB19.5 - YES"
      when
           $step:Step(current.code=="CB19.5"&&answer=="yes");
      then
           $step.setNextQ("CB19.6");
           end
rule "Step CB19.5 - NO"
      when
            $step:Step(current.code=="CB19.5"&&answer=="no");
      then
           $step.setNextQ("CB19.7.1");
           end
rule "Step CB19.6 - YES"
      when
           $step:Step(current.code=="CB19.6"&&answer=="yes");
      then
           $step.setNextQ("CB19.7.1");
           end
rule "Step CB19.6 - NO"
      when
            $step:Step(current.code=="CB19.6"&&answer=="no");
      then
           $step.setNextQ("CB20.1");
           end

rule "Step CB19.7.1 - YES"
      when
           $step:Step(current.code=="CB19.7.1"&&answer=="yes");
      then
           $step.setNextQ("CB20.1");
           end
rule "Step CB19.7.1 - NO"
      when
            $step:Step(current.code=="CB19.7.1"&&answer=="no");
      then
           $step.setNextQ("CB19.7.2");
           end

rule "Step CB19.7.2 - YES"
      when
           $step:Step(current.code=="CB19.7.2"&&answer=="yes");
      then
           $step.setTestFailed();
           end
rule "Step CB19.7.2 - NO"
      when
            $step:Step(current.code=="CB19.7.2"&&answer=="no");
      then
           $step.setNextQ("CB20.1");
           end

rule "Step CB20.1 - YES"
      when
           $step:Step(current.code=="CB20.1"&&answer=="yes");
      then
           $step.setNextQ("CB20.2.2");
           end
rule "Step CB20.1 - NO(with_condition)"
      when
            $step:Step(current.code=="CB20.1"&&answer=="no_with_condition");
      then
           $step.setNextQ("CB20.2.1");
           end
rule "Step CB20.1 - NO (with step)"
      when
           $step:Step(current.code=="CB20"&&answer=="no_with_step");
      then
           $step.setNextQ("CB21.1");
           end
rule "Step CB20.1 - NO(not_condition)"
      when
            $step:Step(current.code=="CB20.1"&&answer=="no_not_condition");
      then
           $step.setNextQ("CB22");
           end

rule "Step CB20.2.1 - YES"
      when
            $step:Step(current.code=="CB20.2.1"&&answer=="yes");
      then
           $step.setNextQ("CB21.1");
           end

rule "Step CB20.2.1 - NO"
      when
            $step:Step(current.code=="CB20.2.1"&&answer=="no");
      then
           $step.setTestFailed();
           end
rule "Step CB20.2.2 - YES"
      when
            $step:Step(current.code=="CB20.2.2"&&answer=="yes");
      then
           $step.setNextQ("CB22");
           end

rule "Step CB20.2.2 - NO"
      when
            $step:Step(current.code=="CB20.2.2"&&answer=="no");
      then
           $step.setTestFailed();
           end

rule "Step CB21.1 - YES"
      when
            $step:Step(current.code=="CB21.1"&&answer=="yes");
      then
           $step.setNextQ("CB21.2");
           end
rule "Step CB21.1 - NO"
      when
            $step:Step(current.code=="CB21.1"&&answer=="no");
      then
           $step.setNextQ("CB21.2");
           end
rule "Step CB21.2 - YES"
      when
            $step:Step(current.code=="CB21.2"&&answer=="yes");
      then
           $step.setNextQ("CB21.3");
           end
rule "Step CB21.2 - NO"
      when
            $step:Step(current.code=="CB21.2"&&answer=="no");
      then
           $step.setNextQ("CB21.3");
           end

rule "Step CB21.3 - YES"
      when
            $step:Step(current.code=="CB21.3"&&answer=="yes");
      then
           $step.setTestFailed();
           end
rule "Step CB21.3 - NO"
      when
            $step:Step(current.code=="CB21.3"&&answer=="no");
      then
           $step.setNextQ("CB21.4");
           end


rule "Step CB21.4 - YES"
      when
            $step:Step(current.code=="CB21.4"&&answer=="yes");
      then
            $step.setTestFailed();
            end
rule "Step CB21.4 - NO"
      when
            $step:Step(current.code=="CB21.4"&&answer=="no");
      then
           $step.setNextQ("CB21.5");
           end

rule "Step CB21.5 - YES"
      when
            $step:Step(current.code=="CB21.5"&&answer=="yes");
      then
            $step.setNextQ("CB21.5.1");
            end
rule "Step CB21.5 - NO"
      when
            $step:Step(current.code=="CB21.5"&&answer=="no");
      then
           $step.setNextQ("CB22");
           end


rule "Step CB21.5.1 - YES"
      when
            $step:Step(current.code=="CB21.5.1"&&answer=="yes");
      then
           $step.setNextQ("CB22");
           end
rule "Step CB21.5.1 - NO"
      when
            $step:Step(current.code=="CB21.5.1"&&answer=="no");
      then
            $step.setTestFailed();
            end


rule "Step CB22 - YES"
      when
            $step:Step(current.code=="CB22"&&answer=="yes");
      then
           $step.setNextQ("CB23");
           end
rule "Step CB22 - NO"
      when
            $step:Step(current.code=="CB22"&&answer=="no");
      then
           $step.setNextQ("CB24");
           end

rule "Step CB23 - YES"
      when
            $step:Step(current.code=="CB23"&&answer=="yes");
      then
           $step.setNextQ("CB24");
           end
rule "Step CB23 - NO"
      when
            $step:Step(current.code=="CB23"&&answer=="no");
      then
           $step.setNextQ("CB23.1");
           end

rule "Step CB23.1 - YES"
      when
            $step:Step(current.code=="CB23.1"&&answer=="yes");
      then
           $step.setNextQ("CB23.2");
           end
rule "Step CB23.1 - NO"
      when
            $step:Step(current.code=="CB23.1"&&answer=="no");
      then
           $step.setNextQ("CB23.2");
           end
rule "Step CB23.2 - YES"
      when
            $step:Step(current.code=="CB23.2"&&answer=="yes");
      then
            $step.setTestFailed();
            end
rule "Step CB23.2 - NO"
      when
            $step:Step(current.code=="CB23.2"&&answer=="no");
      then
           $step.setNextQ("CB23.3");
           end

rule "Step CB23.3 - YES"
      when
            $step:Step(current.code=="CB23.3"&&answer=="yes");
      then
           $step.setNextQ("CB23.3.1");
           end
rule "Step CB23.3 - NO"
      when
            $step:Step(current.code=="CB23.3"&&answer=="no");
      then
           $step.setNextQ("CB24");
           end

rule "Step CB23.3.1 - YES"
      when
            $step:Step(current.code=="CB23.3.1"&&answer=="yes");
      then
           $step.setNextQ("CB24");
           end
rule "Step CB23.3.1 - NO"
      when
            $step:Step(current.code=="CB23.3.1"&&answer=="no");
      then
            $step.setTestFailed();
            end

rule "Step CB24 - YES"
      when
            $step:Step(current.code=="CB24"&&answer=="yes");
      then
           $step.setNextQ("CB25");
           end
rule "Step CB24 - NO"
      when
            $step:Step(current.code=="CB24"&&answer=="no");
      then
           $step.setNextQ("CB27");
           end

rule "Step CB25 - YES"
      when
            $step:Step(current.code=="CB25"&&answer=="yes");
      then
           $step.setNextQ("CB25.1");
           end
rule "Step CB25 - NO"
      when
            $step:Step(current.code=="CB25"&&answer=="no");
      then
           $step.setNextQ("CB26");
           end
rule "Step CB25.1 - YES"
      when
            $step:Step(current.code=="CB25.1"&&answer=="yes");
      then
           $step.setNextQ("CB25.2");
           end
rule "Step CB25.1 - NO"
      when
            $step:Step(current.code=="CB25.1"&&answer=="no");
      then
           $step.setNextQ("CB33");
           end

rule "Step CB25.2 - YES"
      when
            $step:Step(current.code=="CB25.2"&&answer=="yes");
      then
           $step.setNextQ("CB33");
           end
rule "Step CB25.2 - NO"
      when
            $step:Step(current.code=="CB25.2"&&answer=="no");
      then
           $step.setNextQ("CB26");
           end

rule "Step CB26 - YES"
      when
            $step:Step(current.code=="CB26"&&answer=="yes");
      then
           $step.setNextQ("CB26.1");
           end
rule "Step CB26 - NO"
      when
            $step:Step(current.code=="CB26"&&answer=="no");
      then
           $step.setNextQ("CB31.3");
           end

rule "Step CB26.1 - YES"
      when
            $step:Step(current.code=="CB26.1"&&answer=="yes");
      then
           $step.setNextQ("CB33");
           end
rule "Step CB26.1 - NO"
      when
            $step:Step(current.code=="CB26.1"&&answer=="no");
      then
           $step.setNextQ("CB31.3");
           end

rule "Step CB27 - YES"
      when
            $step:Step(current.code=="CB27"&&answer=="yes");
      then
           $step.setNextQ("CB33");
           end
rule "Step CB27 - NO"
      when
            $step:Step(current.code=="CB27"&&answer=="no");
      then
           $step.setNextQ("CB28");
           end

rule "Step CB28 - YES"
      when
            $step:Step(current.code=="CB28"&&answer=="yes");
      then
           $step.setNextQ("CB29");
           end
rule "Step CB28 - NO"
      when
            $step:Step(current.code=="CB28"&&answer=="no");
      then
           $step.setNextQ("CB33");
            end
rule "Step CB29 - YES"
      when
            $step:Step(current.code=="CB29"&&answer=="yes");
      then
           $step.setNextQ("CB30");
           end
rule "Step CB29 - NO"
      when
            $step:Step(current.code=="CB29"&&answer=="no");
      then
           $step.setNextQ("CB31.1");
            end
 rule "Step CB30 - YES"
       when
             $step:Step(current.code=="CB30"&&answer=="yes");
       then
            $step.setNextQ("CB31.1");
            end
 rule "Step CB30 - NO"
       when
             $step:Step(current.code=="CB30"&&answer=="no");
       then
            $step.setNextQ("CB33");
            end

 rule "Step CB31.1 - YES"
       when
             $step:Step(current.code=="CB31.1"&&answer=="yes");
       then
            $step.setNextQ("CB31.2");
            end
 rule "Step CB31.1 - NO"
       when
             $step:Step(current.code=="CB31.1"&&answer=="no");
       then
            $step.setNextQ("CB31.3");
            end

 rule "Step CB31.2 - YES"
       when
             $step:Step(current.code=="CB31.2"&&answer=="yes");
       then
            $step.setNextQ("CB33");
            end
 rule "Step CB31.2 - NO"
       when
             $step:Step(current.code=="CB31.2"&&answer=="no");
       then
            $step.setNextQ("CB31.3");
            end

 rule "Step CB31.3 - YES"
       when
             $step:Step(current.code=="CB31.3"&&answer=="yes");
       then
            $step.setNextQ("CB33");
            end
 rule "Step CB31.3 - NO"
       when
             $step:Step(current.code=="CB31.3"&&answer=="no");
       then
            $step.setNextQ("CB32");
            end

 rule "Step CB32 - YES"
       when
             $step:Step(current.code=="CB32"&&answer=="yes");
       then
            $step.setNextQ("CB32.1");
            end
 rule "Step CB32 - NO"
       when
             $step:Step(current.code=="CB32"&&answer=="no");
       then
            $step.setTestFailed();
            end


 rule "Step CB32.1 - YES"
       when
             $step:Step(current.code=="CB32.1"&&answer=="yes");
       then
            $step.setNextQ("CB33");
            end
 rule "Step CB32.1 - NO"
       when
             $step:Step(current.code=="CB32.1"&&answer=="no");
       then
            $step.setTestFailed();
            end

 rule "Step CB33 - YES"
       when
             $step:Step(current.code=="CB33"&&answer=="yes");
       then
            $step.setNextQ("CB34");
            end
 rule "Step CB33 - NO"
       when
             $step:Step(current.code=="CB33"&&answer=="no");
       then
            $step.setNextQ("CB39");
            end
  rule "Step CB34 - YES"
        when
              $step:Step(current.code=="CB34"&&answer=="yes");
        then
             $step.setNextQ("CB42");
             end
  rule "Step CB34 - NO"
        when
              $step:Step(current.code=="CB34"&&answer=="no");
        then
             $step.setNextQ("CB35");
             end
 rule "Step CB35 - YES"
       when
             $step:Step(current.code=="CB35"&&answer=="yes");
       then
            $step.setNextQ("CB36");
            end
 rule "Step CB35 - NO"
       when
             $step:Step(current.code=="CB35"&&answer=="no");
       then
            $step.setNextQ("CB42");
            end

 rule "Step CB36 - YES"
       when
             $step:Step(current.code=="CB36"&&answer=="yes");
       then
            $step.setNextQ("CB39");
            end
 rule "Step CB36 - NO"
       when
             $step:Step(current.code=="CB36"&&answer=="no");
       then
            $step.setNextQ("CB37");
            end
 rule "Step CB37 - YES"
       when
             $step:Step(current.code=="CB37"&&answer=="yes");
       then
            $step.setTestFailed();
            end
 rule "Step CB37 - NO"
       when
             $step:Step(current.code=="CB37"&&answer=="no");
       then
            $step.setNextQ("CB38.1");
            end
 rule "Step CB38.1 - YES"
       when
             $step:Step(current.code=="CB38.1"&&answer=="yes");
       then
            $step.setNextQ("CB38.2");
             end
 rule "Step CB38.1 - NO"
       when
             $step:Step(current.code=="CB38.1"&&answer=="no");
       then
             $step.setNextQ("CB38.2");
             end

 rule "Step CB38.2 - YES"
       when
             $step:Step(current.code=="CB38.2"&&answer=="yes");
       then
             $step.setNextQ("CB38.3");
             end

 rule "Step CB38.2 - NO"
       when
             $step:Step(current.code=="CB38.2"&&answer=="no");
       then
             $step.setNextQ("CB38.3");
             end

 rule "Step CB38.3 - YES"
       when
             $step:Step(current.code=="CB38.3"&&answer=="yes");
       then
            $step.setTestFailed();
            end

 rule "Step CB38.3 - NO"
       when
             $step:Step(current.code=="CB38.3"&&answer=="no");
       then
            $step.setNextQ("CB38.4");
            end
 rule "Step CB38.4 - YES"
       when
             $step:Step(current.code=="CB38.4"&&answer=="yes");
       then
             $step.setNextQ("CB38.4.1");
             end

 rule "Step CB38.4 - NO"
       when
             $step:Step(current.code=="CB38.4"&&answer=="no");
       then
             $step.setNextQ("CB39");
             end

 rule "Step CB38.4.1 - YES"
       when
             $step:Step(current.code=="CB38.4.1"&&answer=="yes");
       then
            $step.setNextQ("CB39");
            end
 rule "Step CB38.4.1 - NO"
       when
             $step:Step(current.code=="CB38.4.1"&&answer=="no");
       then
             $step.setTestFailed();
             end


 rule "Step CB39 - YES"
       when
             $step:Step(current.code=="CB39"&&answer=="yes");
       then
            $step.setNextQ("CB40");
            end
 rule "Step CB39 - NO"
       when
             $step:Step(current.code=="CB39"&&answer=="no");
       then
             $step.setNextQ("CB64");
             end


 rule "Step CB40 - YES"
       when
             $step:Step(current.code=="CB40"&&answer=="yes");
       then
             $step.setTestOK();
             end

 rule "Step CB40 - NO"
       when
             $step:Step(current.code=="CB40"&&answer=="no");
       then
             $step.setNextQ("CB41");
             end
rule "Step CB41 - YES"
       when
             $step:Step(current.code=="CB40"&&answer=="yes");
       then
             $step.setTestOK();
             end

rule "Step CB41 - NO"
       when
             $step:Step(current.code=="CB41"&&answer=="no");
       then
             $step.setNextQ("CB42");
             end

rule "Step CB42 - YES"
       when
             $step:Step(current.code=="CB42"&&answer=="yes");
       then
             $step.setNextQ("CB43");
            end
rule "Step CB42 - NO"
       when
             $step:Step(current.code=="CB42"&&answer=="no");
       then
             $step.setNextQ("CB49");
             end

rule "Step CB43 - YES"
       when
             $step:Step(current.code=="CB43"&&answer=="yes");
       then
             $step.setNextQ("CB45");
             end
 rule "Step CB43 - NO"
       when
             $step:Step(current.code=="CB43"&&answer=="no");
       then
            $step.setNextQ("CB44");
            end
rule "Step CB44 - YES"
       when
             $step:Step(current.code=="CB44"&&answer=="yes");
       then
            $step.setNextQ("CB49");
            end
 rule "Step CB44 - NO"
       when
             $step:Step(current.code=="CB44"&&answer=="no");
       then
             $step.setTestFailed();
             end

rule "Step CB45 - YES"
       when
             $step:Step(current.code=="CB45"&&answer=="yes");
       then
             $step.setNextQ("CB46");
             end
rule "Step CB45 - NO"
       when
             $step:Step(current.code=="CB45"&&answer=="no");
       then
            $step.setTestFailed();
            end
rule "Step CB46 - YES"
         when
               $step:Step(current.code=="CB46"&&answer=="yes");
         then
               $step.setNextQ("CB47");
               end
rule "Step CB46 - NO"
         when
               $step:Step(current.code=="CB46"&&answer=="no");
         then
            $step.setTestFailed();
            end
rule "Step CB47 - YES"
         when
               $step:Step(current.code=="CB47"&&answer=="yes");
         then
            $step.setTestFailed();
            end
rule "Step CB47 - NO"
         when
               $step:Step(current.code=="CB47"&&answer=="no");
         then
               $step.setNextQ("CB48");
               end

rule "Step CB48 - YES"
         when
               $step:Step(current.code=="CB48"&&answer=="yes");
         then
              $step.setNextQ("CB49");
              end
rule "Step CB48 - NO"
         when
               $step:Step(current.code=="CB48"&&answer=="no");
         then
              $step.setTestFailed();
              end

rule "Step CB49 - YES"
         when
               $step:Step(current.code=="CB49"&&answer=="yes");
         then
              $step.setNextQ("CB49.1.1");
              end
rule "Step CB49 - NO (with_component)"
         when
               $step:Step(current.code=="CB49"&&answer=="with_component");
         then
              $step.setNextQ("CB49.1.2");
              end
rule "Step CB49 - NO(no_component)"
         when
               $step:Step(current.code=="CB49"&&answer=="no_component");
         then
              $step.setNextQ("CB54");
              end
rule "Step CB49 - NO"
         when
               $step:Step(current.code=="CB49"&&answer=="no");
         then
              $step.setTestOK();
              end

rule "Step CB49.1.1 - YES"
         when
               $step:Step(current.code=="CB49.1.1"&&answer=="yes");
         then
              $step.setTestOK();
              end

rule "Step CB49.1.1 - NO"
         when
               $step:Step(current.code=="CB49.1.1"&&answer=="no");
         then
              $step.setNextQ("CB50.1");
              end


rule "Step CB49.1.2 - YES"
         when
               $step:Step(current.code=="CB49.1.2"&&answer=="yes");
         then
            $step.setNextQ("CB54");
            end

rule "Step CB49.1.2 - NO"
         when
               $step:Step(current.code=="CB49.1.2"&&answer=="no");
         then
            $step.setNextQ("CB50.2");
            end


 rule "Step CB50.1 - FIXED"
       when
            $step:Step(current.code=="CB50.1"&&answer=="fixed");
       then
            $step.setNextQ("CB52.1.1");
            end


rule "Step CB50.1 - FLOAT"
       when
             $step:Step(current.code=="CB50.1"&&answer=="floating");
       then
            $step.setNextQ("CB51.1.1");
            end

rule "Step CB51.1.1 - YES"
       when
            $step:Step(current.code=="CB51.1.1"&&answer=="yes");
       then
            $step.setNextQ("CB51.2.1");
            end
rule "Step CB51.1.1 - NO"
       when
             $step:Step(current.code=="CB51.1.1"&&answer=="no");
       then
              $step.setTestFailed();
              end
rule "Step CB51.2.1 - YES"
       when
            $step:Step(current.code=="CB51.2.1"&&answer=="yes");
       then
              $step.setTestFailed();
               end
rule "Step CB51.2.1 - NO"
       when
             $step:Step(current.code=="CB51.2.1"&&answer=="no");
       then
            $step.setNextQ("CB51.3.1");
            end
rule "Step CB51.3.1 - YES"
       when
            $step:Step(current.code=="CB51.3.1"&&answer=="yes");
       then
              $step.setTestFailed();
               end
rule "Step CB51.3.1 - NO"
       when
             $step:Step(current.code=="CB51.3.1"&&answer=="no");
       then
            $step.setNextQ("CB51.4.1");
            end

rule "Step CB51.4.1 - YES"
       when
            $step:Step(current.code=="CB51.4.1"&&answer=="yes");
       then
            $step.setNextQ("CB51.5.1");
            end
rule "Step CB51.4.1 - NO"
       when
             $step:Step(current.code=="CB51.4.1"&&answer=="no");
       then
              $step.setNextQ("CB51.7.1.1");
              end
rule "Step CB51.5.1 - YES"
       when
            $step:Step(current.code=="CB51.5.1"&&answer=="yes");
       then
            $step.setNextQ("CB51.6.1");
            end
rule "Step CB51.5.1 - NO"
       when
             $step:Step(current.code=="CB51.5.1"&&answer=="no");
       then
            $step.setNextQ("CB51.7.1.1");
            end
rule "Step CB51.6.1 - YES"
       when
            $step:Step(current.code=="CB51.6.1"&&answer=="yes");
       then
            $step.setNextQ("CB51.7.1.1");
            end
rule "Step CB51.6.1 - NO"
       when
             $step:Step(current.code=="CB51.6.1"&&answer=="no");
       then
            $step.setNextQ("CB52.1.1");
            end

rule "Step CB51.7.1.1 - YES"
       when
            $step:Step(current.code=="CB51.7.1.1"&&answer=="yes");
       then
            $step.setNextQ("CB52.1.1");
            end
rule "Step CB51.7.1.1 - NO"
       when
             $step:Step(current.code=="CB51.7.1.1"&&answer=="no");
       then
            $step.setNextQ("CB51.7.2.1");
            end

rule "Step CB51.7.2.1 - YES"
       when
            $step:Step(current.code=="CB51.7.2.1"&&answer=="yes");
       then
            $step.setTestFailed();
            end
rule "Step CB51.7.2.1 - NO"
       when
             $step:Step(current.code=="CB51.7.2.1"&&answer=="no");
       then
            $step.setNextQ("CB52.1.1");
            end

rule "Step CB52.1.1 - YES"
       when
            $step:Step(current.code=="CB52.1.1"&&answer=="yes");
       then
            $step.setNextQ("CB52.2.2.1");
            end
rule "Step CB52.1.1 - NO(with_condition)"
       when
             $step:Step(current.code=="CB52.1.1"&&answer=="no_with_condition");
       then
            $step.setNextQ("CB52.2.1.1");
            end
rule "Step CB52.1.1 - NO (with step)"
       when
            $step:Step(current.code=="CB52.1.1"&&answer=="no_with_step");
       then
            $step.setNextQ("CB53.3.1");
           end
rule "Step CB52.1.1 - NO(not condition)"
       when
             $step:Step(current.code=="CB52.1.1"&&answer=="no_not_condition");
       then
            $step.setTestOK();
            end

rule "Step CB52.2.1.1 - YES"
       when
             $step:Step(current.code=="CB52.2.1.1"&&answer=="yes");
       then
            $step.setNextQ("CB53.1.1");
            end

rule "Step CB52.2.1.1 - NO"
       when
             $step:Step(current.code=="CB52.2.1.1"&&answer=="no");
       then
            $step.setTestFailed();
            end
rule "Step CB52.2.2.1 - YES"
       when
             $step:Step(current.code=="CB52.2.2.1"&&answer=="yes");
       then
            $step.setNextQ("CB54");
            end
rule "Step CB52.2.2.1 - NO"
       when
             $step:Step(current.code=="CB52.2.2.1"&&answer=="no");
       then
            $step.setTestFailed();
            end

rule "Step CB53.1.1 - YES"
       when
             $step:Step(current.code=="CB53.1.1"&&answer=="yes");
       then
            $step.setNextQ("CB53.2.1");
            end
rule "Step CB53.1.1 - NO"
       when
             $step:Step(current.code=="CB53.1.1"&&answer=="no");
       then
            $step.setNextQ("CB53.2.1");
            end
rule "Step CB53.2.1 - YES"
       when
             $step:Step(current.code=="CB53.2.1"&&answer=="yes");
       then
            $step.setNextQ("CB53.3.1");
            end
 rule "Step CB53.2.1 - NO"
       when
             $step:Step(current.code=="CB53.2.1"&&answer=="no");
       then
            $step.setNextQ("CB53.3.1");
            end

 rule "Step CB53.3.1 - YES"
       when
             $step:Step(current.code=="CB53.3.1"&&answer=="yes");
       then
            $step.setTestFailed();
            end
 rule "Step CB53.3.1 - NO"
       when
             $step:Step(current.code=="CB53.3.1"&&answer=="no");
       then
            $step.setNextQ("CB53.4.1");
            end

 rule "Step CB53.4.1 - YES"
       when
             $step:Step(current.code=="CB53.4.1"&&answer=="yes");
       then
            $step.setTestFailed();
            end
 rule "Step CB53.4.1 - NO"
       when
             $step:Step(current.code=="CB53.4.1"&&answer=="no");
       then
            $step.setNextQ("CB53.5.1");
            end

rule "Step CB53.5.1 - YES"
       when
             $step:Step(current.code=="CB53.5.1"&&answer=="yes");
       then
            $step.setNextQ("CB53.5.1.1");
            end
rule "Step CB53.5.1 - NO"
       when
             $step:Step(current.code=="CB53.5.1"&&answer=="no");
       then
            $step.setNextQ("CB54");
            end

rule "Step CB53.5.1.1 - YES"
       when
             $step:Step(current.code=="CB53.5.1.1"&&answer=="yes");
       then
            $step.setNextQ("CB51");
            end
rule "Step CB53.5.1.1 - NO"
       when
             $step:Step(current.code=="CB53.5.1.1"&&answer=="no");
       then
             $step.setTestFailed();
             end

 rule "Step CB50.2 - FIXED"
       when
            $step:Step(current.code=="CB50.2"&&answer=="fixed");
       then
            $step.setNextQ("CB52.1.2");
            end


rule "Step CB50.2 - FLOAT"
       when
             $step:Step(current.code=="CB50.2"&&answer=="floating");
       then
            $step.setNextQ("CB51.1.2");
            end

rule "Step CB51.1.2 - YES"
       when
            $step:Step(current.code=="CB51.1.2"&&answer=="yes");
       then
            $step.setNextQ("CB51.2.2");
            end
rule "Step CB51.1.2 - NO"
       when
             $step:Step(current.code=="CB51.1.2"&&answer=="no");
       then
              $step.setTestFailed();
              end
rule "Step CB51.2.2 - YES"
       when
            $step:Step(current.code=="CB51.2.2"&&answer=="yes");
       then
              $step.setTestFailed();
               end
rule "Step CB51.2.2 - NO"
       when
             $step:Step(current.code=="CB51.2.2"&&answer=="no");
       then
            $step.setNextQ("CB51.3.2");
            end
rule "Step CB51.3.2 - YES"
       when
            $step:Step(current.code=="CB51.3.2"&&answer=="yes");
       then
              $step.setTestFailed();
               end
rule "Step CB51.3.2 - NO"
       when
             $step:Step(current.code=="CB51.3.2"&&answer=="no");
       then
            $step.setNextQ("CB51.4.2");
            end

rule "Step CB51.4.2 - YES"
       when
            $step:Step(current.code=="CB51.4.2"&&answer=="yes");
       then
            $step.setNextQ("CB51.5.2");
            end
rule "Step CB51.4.2 - NO"
       when
             $step:Step(current.code=="CB51.4.2"&&answer=="no");
       then
              $step.setNextQ("CB51.7.1.2");
              end
rule "Step CB51.5.2 - YES"
       when
            $step:Step(current.code=="CB51.5.2"&&answer=="yes");
       then
            $step.setNextQ("CB51.6.2");
            end
rule "Step CB51.5.2 - NO"
       when
             $step:Step(current.code=="CB51.5.2"&&answer=="no");
       then
            $step.setNextQ("CB51.7.1.2");
            end
rule "Step CB51.6.2 - YES"
       when
            $step:Step(current.code=="CB51.6.2"&&answer=="yes");
       then
            $step.setNextQ("CB51.7.1.2");
            end
rule "Step CB51.6.2 - NO"
       when
             $step:Step(current.code=="CB51.6.2"&&answer=="no");
       then
            $step.setNextQ("CB52.1.2");
            end

rule "Step CB51.7.1.2 - YES"
       when
            $step:Step(current.code=="CB51.7.1.2"&&answer=="yes");
       then
            $step.setNextQ("CB52.1.2");
            end
rule "Step CB51.7.1.2 - NO"
       when
             $step:Step(current.code=="CB51.7.1.2"&&answer=="no");
       then
            $step.setNextQ("CB51.7.2.2");
            end

rule "Step CB51.7.2.2 - YES"
       when
            $step:Step(current.code=="CB51.7.2.2"&&answer=="yes");
       then
            $step.setTestFailed();
            end
rule "Step CB51.7.2.2 - NO"
       when
             $step:Step(current.code=="CB51.7.2.2"&&answer=="no");
       then
            $step.setNextQ("CB52.1.2");
            end

rule "Step CB52.1.2 - YES"
       when
            $step:Step(current.code=="CB52.1.2"&&answer=="yes");
       then
            $step.setNextQ("CB52.2.2.2");
            end
rule "Step CB52.1.2 - NO(with_condition)"
       when
             $step:Step(current.code=="CB52.1.2"&&answer=="no_with_condition");
       then
            $step.setNextQ("CB52.2.1.2");
            end
rule "Step CB52.1.2 - NO (with step)"
       when
            $step:Step(current.code=="CB52.1.2"&&answer=="no_with_step");
       then
            $step.setNextQ("CB53.3.2");
           end
rule "Step CB52.1.2 - NO(not condition)"
       when
             $step:Step(current.code=="CB52.1.2"&&answer=="no_not_condition");
       then
            $step.setTestOK();
            end

rule "Step CB52.2.1.2 - YES"
       when
             $step:Step(current.code=="CB52.2.1.2"&&answer=="yes");
       then
            $step.setNextQ("CB53.1.2");
            end

rule "Step CB52.2.1.2 - NO"
       when
             $step:Step(current.code=="CB52.2.1.2"&&answer=="no");
       then
            $step.setTestFailed();
            end
rule "Step CB52.2.2.2 - YES"
       when
             $step:Step(current.code=="CB52.2.2.2"&&answer=="yes");
       then
            $step.setNextQ("CB54");
            end
rule "Step CB52.2.2.2 - NO"
       when
             $step:Step(current.code=="CB52.2.2.2"&&answer=="no");
       then
            $step.setTestFailed();
            end

rule "Step CB53.1.2 - YES"
       when
             $step:Step(current.code=="CB53.1.2"&&answer=="yes");
       then
            $step.setNextQ("CB53.2.2");
            end
rule "Step CB53.1.2 - NO"
       when
             $step:Step(current.code=="CB53.1.2"&&answer=="no");
       then
            $step.setNextQ("CB53.2.2");
            end
rule "Step CB53.2.2 - YES"
       when
             $step:Step(current.code=="CB53.2.2"&&answer=="yes");
       then
            $step.setNextQ("CB53.3.2");
            end
 rule "Step CB53.2.2 - NO"
       when
             $step:Step(current.code=="CB53.2.2"&&answer=="no");
       then
            $step.setNextQ("CB53.3.2");
            end

 rule "Step CB53.3.2 - YES"
       when
             $step:Step(current.code=="CB53.3.2"&&answer=="yes");
       then
            $step.setTestFailed();
            end
 rule "Step CB53.3.2 - NO"
       when
             $step:Step(current.code=="CB53.3.2"&&answer=="no");
       then
            $step.setNextQ("CB53.4.2");
            end

 rule "Step CB53.4.2 - YES"
       when
             $step:Step(current.code=="CB53.4.2"&&answer=="yes");
       then
            $step.setTestFailed();
            end
 rule "Step CB53.4.2 - NO"
       when
             $step:Step(current.code=="CB53.4.2"&&answer=="no");
       then
            $step.setNextQ("CB53.5.2");
            end

rule "Step CB53.5.2 - YES"
       when
             $step:Step(current.code=="CB53.5.2"&&answer=="yes");
       then
            $step.setNextQ("CB53.5.1.2");
            end
rule "Step CB53.5.2 - NO"
       when
             $step:Step(current.code=="CB53.5.2"&&answer=="no");
       then
            $step.setNextQ("CB54");
            end

rule "Step CB53.5.1.2 - YES"
       when
             $step:Step(current.code=="CB53.5.1.2"&&answer=="yes");
       then
            $step.setNextQ("CB54");
            end
rule "Step CB53.5.1.2 - NO"
       when
             $step:Step(current.code=="CB53.5.1.2"&&answer=="no");
       then
             $step.setTestFailed();
             end




rule "Step CB54 - YES"
       when
             $step:Step(current.code=="CB54"&&answer=="yes");
       then
            $step.setNextQ("CB55");
            end

rule "Step CB54 - NO"
       when
             $step:Step(current.code=="CB54"&&answer=="no");
       then
            $step.setNextQ("CB60");
            end

rule "Step CB55 - YES"
       when
             $step:Step(current.code=="CB55"&&answer=="yes");
       then
            $step.setNextQ("CB56");
             end
rule "Step CB55 - NO"
       when
             $step:Step(current.code=="CB55"&&answer=="no");
       then
            $step.setTestFailed();
            end

//-----------
rule "Step CB56 - FIXED"
      when
           $step:Step(current.code=="CB56"&&answer=="fixed");
      then
           $step.setNextQ("CB58.1");
           end
rule "Step CB56 - FLOAT"
      when
            $step:Step(current.code=="CB56"&&answer=="floating");
      then
           $step.setNextQ("CB57.1");
           end

rule "Step CB57.1 - YES"
      when
           $step:Step(current.code=="CB57.1"&&answer=="yes");
      then
           $step.setNextQ("CB57.2");
           end
rule "Step CB57.1 - NO"
      when
            $step:Step(current.code=="CB57.1"&&answer=="no");
      then
             $step.setTestFailed();
             end

rule "Step CB57.2 - YES"
      when
           $step:Step(current.code=="CB57.2"&&answer=="yes");
      then
             $step.setTestFailed();
             end
rule "Step CB57.2 - NO"
      when
            $step:Step(current.code=="CB57.2"&&answer=="no");
      then
           $step.setNextQ("CB57.3");
           end
rule "Step CB57.3 - YES"
      when
           $step:Step(current.code=="CB57.3"&&answer=="yes");
      then
             $step.setTestFailed();
             end
rule "Step CB57.3 - NO"
      when
            $step:Step(current.code=="CB57.3"&&answer=="no");
      then
           $step.setNextQ("CB57.4");
           end

rule "Step CB57.4 - YES"
      when
           $step:Step(current.code=="CB57.4"&&answer=="yes");
      then
           $step.setNextQ("CB57.5");
           end
rule "Step CB57.4 - NO"
      when
            $step:Step(current.code=="CB57.4"&&answer=="no");
      then
             $step.setNextQ("CB57.7.1");
             end
rule "Step CB57.5 - YES"
      when
           $step:Step(current.code=="CB57.5"&&answer=="yes");
      then
           $step.setNextQ("CB57.6");
           end
rule "Step CB57.5 - NO"
      when
            $step:Step(current.code=="CB57.5"&&answer=="no");
      then
           $step.setNextQ("CB57.7.1");
           end
rule "Step CB57.6 - YES"
      when
           $step:Step(current.code=="CB57.6"&&answer=="yes");
      then
           $step.setNextQ("CB57.7.1");
           end
rule "Step CB57.6 - NO"
      when
            $step:Step(current.code=="CB57.6"&&answer=="no");
      then
           $step.setNextQ("CB58.1");
           end

rule "Step CB57.7.1 - YES"
      when
           $step:Step(current.code=="CB57.7.1"&&answer=="yes");
      then
           $step.setNextQ("CB58.1");
           end
rule "Step CB57.7.1 - NO"
      when
            $step:Step(current.code=="CB57.7.1"&&answer=="no");
      then
           $step.setNextQ("CB57.7.2");
           end

rule "Step CB57.7.2 - YES"
      when
           $step:Step(current.code=="CB57.7.1"&&answer=="yes");
      then
           $step.setTestFailed();
           end
rule "Step CB57.7.2 - NO"
      when
            $step:Step(current.code=="CB57.7.2"&&answer=="no");
      then
           $step.setNextQ("CB58.1");
           end

rule "Step CB58.1 - YES"
      when
           $step:Step(current.code=="CB58.1"&&answer=="yes");
      then
           $step.setNextQ("CB58.2.2");
           end
rule "Step CB58.1 - NO(with_condition)"
      when
            $step:Step(current.code=="CB58.1"&&answer=="no_with_condition");
      then
           $step.setNextQ("CB8.2.1");
           end
rule "Step CB58.1 - NO (with step)"
      when
           $step:Step(current.code=="CB58.1"&&answer=="no_with_step");
      then
           $step.setNextQ("CB59.1");
           end
rule "Step CB58.1 - NO(not_condition)"
      when
            $step:Step(current.code=="CB58.1"&&answer=="no_not_condition");
      then
           $step.setNextQ("CB10");
           end

rule "Step CB58.2.2 - NO"
      when
            $step:Step(current.code=="CB58.2.1"&&answer=="no");
      then
           $step.setTestFailed();
           end

rule "Step CB59.1 - YES"
      when
            $step:Step(current.code=="CB59.1"&&answer=="yes");
      then
           $step.setNextQ("CB59.2");
           end
rule "Step CB59.1 - NO"
      when
            $step:Step(current.code=="CB59.1"&&answer=="no");
      then
           $step.setNextQ("CB59.2");
           end
rule "Step CB59.2 - YES"
      when
            $step:Step(current.code=="CB59.2"&&answer=="yes");
      then
           $step.setNextQ("CB59.3");
           end


rule "Step CB59.3 - YES"
      when
            $step:Step(current.code=="CB59.3"&&answer=="yes");
      then
           $step.setTestFailed();
           end
rule "Step CB59.3 - NO"
      when
            $step:Step(current.code=="CB59.3"&&answer=="no");
      then
           $step.setNextQ("CB59.4");
           end

rule "Step CB59.4 - YES"
      when
            $step:Step(current.code=="CB59.4"&&answer=="yes");
      then
            $step.setTestFailed();
            end
rule "Step CB59.4 - NO"
      when
            $step:Step(current.code=="CB59.4"&&answer=="no");
      then
           $step.setNextQ("CB59.5");
           end

rule "Step CB59.5 - YES"
      when
            $step:Step(current.code=="CB59.5"&&answer=="yes");
      then
           $step.setNextQ("CB59.5.1");
           end
rule "Step CB59.5 - NO"
      when
            $step:Step(current.code=="CB59.5"&&answer=="no");
      then
           $step.setNextQ("CB60");
           end

rule "Step CB59.5.1 - YES"
      when
            $step:Step(current.code=="CB59.5.1"&&answer=="yes");
      then
           $step.setNextQ("CB60");
           end
rule "Step CB59.5.1 - NO"
      when
            $step:Step(current.code=="CB59.5.1"&&answer=="no");
      then
           $step.setTestFailed();
           end


 rule "Step CB60 - YES"
       when
             $step:Step(current.code=="CB60"&&answer=="yes");
       then
            $step.setNextQ("CB61");
            end
 rule "Step CB60 - NO"
       when
             $step:Step(current.code=="CB60"&&answer=="no");
       then
            $step.setNextQ("CB61");
            end

 rule "Step CB61 - YES"
       when
             $step:Step(current.code=="CB61"&&answer=="yes");
       then
            $step.setNextQ("CB62");
            end
rule "Step CB61 - NO"
       when
             $step:Step(current.code=="CB61"&&answer=="no");
       then
            $step.setNextQ("CB62");
             end

rule "Step CB61 - No_amount"
         when
               $step:Step(current.code=="CB61"&&answer=="no_amount_update");
         then
               $step.setTestFailed();
               end

rule "Step CB62 - YES"
         when
               $step:Step(current.code=="CB62"&&answer=="yes");
         then
               $step.setTestFailed();
               end

rule "Step CB62 - NO"
         when
               $step:Step(current.code=="CB62"&&answer=="yes");
         then
            $step.setNextQ("CB63");
               end


rule "Step CB63 - YES"
          when
                $step:Step(current.code=="CB63"&&answer=="yes");
          then
           $step.setNextQ("CB63.1");
           end
rule "Step CB63 - NO"
          when
                $step:Step(current.code=="CB63"&&answer=="no");
          then
           $step.setTestOK();
           end

rule "Step CB63.1 - YES"
          when
                $step:Step(current.code=="CB63.1"&&answer=="yes");
          then
           $step.setTestOK();
           end
rule "Step CB63.1 - NO"
          when
                $step:Step(current.code=="CB63.1"&&answer=="no");
          then
           $step.setTestFailed();
           end

rule "Step CB64 - YES"
          when
                $step:Step(current.code=="CB64"&&answer=="yes");
          then
                $step.setNextQ("CB65");
                end
rule "Step CB64 - NO"
          when
                $step:Step(current.code=="CB64"&&answer=="no");
          then
           $step.setTestOK();
           end

rule "Step CB65 - YES"
          when
                $step:Step(current.code=="CB64"&&answer=="yes");
          then
                $step.setTestFailed();
                end
rule "Step CB65 - NO"
          when
                $step:Step(current.code=="CB65"&&answer=="no");
          then
           $step.setTestOK();
           end                     