import com.egartech.sppi.model.Step;
import com.egartech.sppi.model.Product;



rule "define first question of Termination or suspension of obligations test"
    when
        product:Product(productCode=="termination_or_suspension_of_obligations");
    then
        product.setFirstQuestionCode("STEP_1");
        update(product);
end

rule "Yes to 1 question of Termination or suspension of obligations test"
    when
        step:Step(current.code=="STEP_1"&&answer=="yes");
    then
        step.setNextQ("STEP_2");
        update(step);
end

rule "No to 1 question of Termination or suspension of obligations test"
    when
        step:Step(current.code=="STEP_1"&&answer=="no");
    then
        step.setNextQ("FAIL");
        update(step);
end

rule "Yes to 2 question of Termination or suspension of obligations test"
    when
        step:Step(current.code=="STEP_2"&&answer=="yes");
    then
        step.setNextQ("STEP_3.1");
        update(step);
end

rule "No to 2 question of Termination or suspension of obligations test"
    when
        step:Step(current.code=="STEP_2"&&answer=="no");
    then
        step.setNextQ("STEP_4");
        update(step);
end

rule "Yes to 3.1 question of Termination or suspension of obligations test"
    when
        step:Step(current.code=="STEP_3.1"&&answer=="yes");
    then
        step.setNextQ("FAIL");
        update(step);
end

rule "No to 3.1 question of Termination or suspension of obligations test"
    when
        step:Step(current.code=="STEP_3.1"&&answer=="no");
    then
        step.setNextQ("STEP_3.2");
        update(step);
end

rule "Yes to 3.2 question of Termination or suspension of obligations test"
    when
        step:Step(current.code=="STEP_3.2"&&answer=="yes");
    then
        step.setNextQ("STEP_3.3");
        update(step);
end

rule "No to 3.2 question of Termination or suspension of obligations test"
    when
        step:Step(current.code=="STEP_3.2"&&answer=="no");
    then
        step.setNextQ("FAIL");
        update(step);
end

rule "Yes to 3.3 question of Termination or suspension of obligations test"
    when
        step:Step(current.code=="STEP_3.3"&&answer=="yes");
    then
        step.setNextQ("STEP_3.4");
        update(step);
end

rule "No to 3.3 question of Termination or suspension of obligations test"
    when
        step:Step(current.code=="STEP_3.3"&&answer=="no");
    then
        step.setNextQ("FAIL");
        update(step);
end

rule "Yes to 3.4 question of Termination or suspension of obligations test"
    when
        step:Step(current.code=="STEP_3.4"&&answer=="yes");
    then
        step.setNextQ("FAIL");
        update(step);
end

rule "No to 3.4 question of Termination or suspension of obligations test"
    when
        step:Step(current.code=="STEP_3.4"&&answer=="no");
    then
        step.setNextQ("STEP_3.5");
        update(step);
end

rule "Yes to 3.5 question of Termination or suspension of obligations test"
    when
        step:Step(current.code=="STEP_3.5"&&answer=="yes");
    then
        step.setNextQ("STEP_4");
        update(step);
end

rule "No to 3.5 question of Termination or suspension of obligations test"
    when
        step:Step(current.code=="STEP_3.5"&&answer=="no");
    then
        step.setNextQ("STEP_3.6");
        update(step);
end

rule "Yes to 3.6 question of Termination or suspension of obligations test"
    when
        step:Step(current.code=="STEP_3.6"&&answer=="yes");
    then
        step.setNextQ("STEP_4");
        update(step);
end

rule "No to 3.6 question of Termination or suspension of obligations test"
    when
        step:Step(current.code=="STEP_3.6"&&answer=="no");
    then
        step.setNextQ("FAIL");
        update(step);
end

rule "Yes to 4 question of Termination or suspension of obligations test"
    when
        step:Step(current.code=="STEP_4"&&answer=="yes");
    then
        step.setNextQ("SUCCESS");
        update(step);
end

rule "No to 4 question of Termination or suspension of obligations test"
    when
        step:Step(current.code=="STEP_4"&&answer=="no");
    then
        step.setNextQ("STEP_5");
        update(step);
end

rule "Yes to 5 question of Termination or suspension of obligations test"
    when
        step:Step(current.code=="STEP_5"&&answer=="yes");
    then
        step.setNextQ("SUCCESS");
        update(step);
end

rule "No to 5 question of Termination or suspension of obligations test"
    when
        step:Step(current.code=="STEP_5"&&answer=="no");
    then
        step.setNextQ("FAIL");
        update(step);
end