import com.egartech.sppi.model.Step;
import com.egartech.sppi.model.Product;

rule "define first question of test"
    when
        $product:Product(productCode=="update");
    then
        $product.setFirstQuestionCode("UPD1.1");
end

rule "Step UPD1.1 - YES"
    when
        $step:Step(current.code=="UPD1.1"&& answer=="yes");
    then
        $step.setTestFailed();
end

rule "Step UPD1.1 - NO"
    when
        $step:Step(current.code=="UPD1.1"&&answer=="no");
    then
        $step.setNextQ("UPD1.2");
        
end

rule "Step UPD1.2 - YES"
    when
        $step:Step(current.code=="UPD1.2"&& answer=="yes")
    then
        $step.setTestFailed();
end

rule "Step UPD1.2 - NO"
    when
        $step:Step(current.code=="UPD1.2"&&answer=="no");
    then
        $step.setNextQ("UPD1.3");
end

rule "Step UPD1.3 - YES"
    when
        $step:Step(current.code=="UPD1.3"&& answer=="yes")
    then
        $step.setTestFailed();
end

rule "Step UPD1.3 - NO"
    when
        $step:Step(current.code=="UPD1.3"&&answer=="no");
    then
        $step.setNextQ("UPD1.4");
end

rule "Step UPD1.4 - YES"
    when
        $step:Step(current.code=="UPD1.4"&& answer=="yes")
    then
        $step.setTestFailed();
end

rule "Step UPD1.4 - NO"
    when
        $step:Step(current.code=="UPD1.4"&&answer=="no");
    then
        $step.setNextQ("UPD2");
end

rule "Step UPD2 - YES"
    when
        $step:Step(current.code=="UPD2"&&answer=="yes");
    then
        $step.setNextQ("UPD3");
        
end
rule "Step UPD2 - NO"
     when
         $step:Step(current.code=="UPD2" && answer=="no");
     then
         $step.setNextQ("UPD5");
end
rule "Step UPD3 - YES"
     when
         $step:Step(current.code=="UPD3"&&answer=="yes");
     then
         $step.setTestFailed();
         
end

rule "Step UPD3 - NO"
     when
         $step:Step(current.code=="UPD3"&&answer=="no");
     then
        $step.setNextQ("UPD4");
        
end
rule "Step UPD4 - YES"
     when
         $step:Step(current.code=="UPD4"&&answer=="yes");
     then
         $step.setTestFailed();
         
end
rule "Step UPD4 - NO"
     when
         $step:Step(current.code=="UPD4"&&answer=="no");
     then
        $step.setNextQ("UPD5");
        
end

rule "Step UPD5 - YES"
     when
         $step:Step(current.code=="UPD5"&&answer=="yes");
     then
         $step.setNextQ("UPD6");
         
end
rule "Step UPD5 - NO"
     when
         $step:Step(current.code=="UPD5"&&answer=="no");
     then
        $step.setTestFailed();
        
end
rule "Step UPD6 - YES"
      when
          $step:Step(current.code=="UPD6"&&answer=="yes");
      then
          $step.setNextQ("UPD7");
          
end
rule "Step UPD6 - NO"
      when
          $step:Step(current.code=="UPD6"&&answer=="no");
      then
         $step.setNextQ("UPD7");
         
end
rule "Step UPD7 - YES"
      when
          $step:Step(current.code=="UPD7"&&answer=="yes");
      then
          $step.setTestOK();
          
end
rule "Step UPD7 - NO"
      when
          $step:Step(current.code=="UPD7"&&answer=="no");
      then
         $step.setNextQ("UPD8");
         
end
rule "Step UPD8 - YES"
      when
          $step:Step(current.code=="UPD8"&&answer=="yes");
      then
          $step.setNextQ("UPD9.1");
          
end
rule "Step UPD8 - NO"
      when
          $step:Step(current.code=="UPD8"&&answer=="no");
      then
         $step.setNextQ("UPD10");
         
end
rule "Step UPD9.1 - YES"
      when
          $step:Step(current.code=="UPD9.1"&&answer=="yes");
      then
          $step.setNextQ("UPD10");
          
end
rule "Step UPD9.1 - NO"
      when
          $step:Step(current.code=="UPD9.1"&&answer=="no");
      then
         $step.setNextQ("UPD9.2");
         
end
rule "Step UPD9.2 - YES"
      when
          $step:Step(current.code=="UPD9.2"&&answer=="yes");
      then
          $step.setNextQ("UPD9.3");
          
end
rule "Step UPD9.2 - NO"
      when
          $step:Step(current.code=="UPD9.2"&&answer=="no");
      then
         $step.setNextQ("UPD9.4");
         
end
rule "Step UPD9.3 - YES"
      when
          $step:Step(current.code=="UPD9.3"&&answer=="yes");
      then
          $step.setNextQ("UPD9.4");
          
end
rule "Step UPD9.3 - NO"
      when
          $step:Step(current.code=="UPD9.3"&&answer=="no");
      then
         $step.setNextQ("UPD10");
         
end
rule "Step UPD9.4 - YES"
      when
          $step:Step(current.code=="UPD9.4"&&answer=="yes");
      then
          $step.setNextQ("UPD9.5");
          
end
rule "Step UPD9.4 - NO"
      when
          $step:Step(current.code=="UPD9.4"&&answer=="no");
      then
         $step.setNextQ("UPD9.6");
         
end
rule "Step UPD9.5 - YES"
      when
          $step:Step(current.code=="UPD9.5"&&answer=="yes");
      then
          $step.setNextQ("UPD10");
          
end
rule "Step UPD9.5 - NO"
      when
          $step:Step(current.code=="UPD9.5"&&answer=="no");
      then
         $step.setNextQ("UPD9.6");
         
end
rule "Step UPD9.6 - YES"
      when
          $step:Step(current.code=="UPD9.6"&&answer=="yes");
      then
          $step.setNextQ("UPD10");
          
end
rule "Step UPD9.6 - NO"
      when
          $step:Step(current.code=="UPD9.6"&&answer=="no");
      then
         $step.setNextQ("UPD9.7");
         
end

rule "Step UPD9.7 - YES"
      when
          $step:Step(current.code=="UPD9.7"&&answer=="yes");
      then
          $step.setNextQ("UPD9.8");
          
end
rule "Step UPD9.7 - NO"
      when
          $step:Step(current.code=="UPD9.7"&&answer=="no");
      then
         $step.setTestFailed();
         

end
 rule "Step UPD9.8 - YES"
       when
           $step:Step(current.code=="UPD9.8"&&answer=="yes");
       then
           $step.setNextQ("UPD10");
           
end
 rule "Step UPD9.8 - NO"
       when
           $step:Step(current.code=="UPD9.8"&&answer=="no");
       then
          $step.setTestFailed();
          

end
rule "Step UPD10 - YES"
      when
          $step:Step(current.code=="UPD10"&&answer=="yes");
      then
          $step.setNextQ("UPD12");
          
end
rule "Step UPD10 - NO"
      when
          $step:Step(current.code=="UPD10"&&answer=="no");
      then
         $step.setNextQ("UPD11");
         
end
rule "Step UPD11 - YES"
      when
          $step:Step(current.code=="UPD11"&&answer=="yes");
      then
          $step.setTestFailed();
          
end
rule "Step UPD11 - NO"
      when
          $step:Step(current.code=="UPD11"&&answer=="no");
      then
         $step.setTestOK();
         
end
rule "Step UPD12 - YES"
       when
           $step:Step(current.code=="UPD12"&&answer=="yes");
       then
           $step.setNextQ("UPD13.1");
           
end
rule "Step UPD12 - NO"
       when
           $step:Step(current.code=="UPD12"&&answer=="no");
       then
          $step.setTestFailed();
          
end

rule "Step UPD13 - YES"
      when
          $step:Step(current.code=="UPD13.1"&&answer=="yes"&&current.code=="UPD13.2"&&answer=="yes" );
      then
          $step.setTestOK();
          
end
rule "Step UPD13 - NO"
      when
          $step:Step(current.code=="UPD13.1"&&answer=="no"||current.code=="UPD13.2"&&answer=="no");
      then
         $step.setNextQ("UPD14");
         
end
rule "Step UPD14 - YES"
      when
          $step:Step(current.code=="UPD14"&&answer=="yes" );
      then
          $step.setTestOK();
          
end
rule "Step UPD14 - NO"
      when
          $step:Step(current.code=="UPD14"&&answer=="no");
      then
         $step.setNextQ("UPD15");
end
rule "Step UPD15 - YES"
      when
          $step:Step(current.code=="UPD15"&&answer=="yes" );
      then
          $step.setTestOK();
          
end
rule "Step UPD15 - NO"
      when
          $step:Step(current.code=="UPD15"&&answer=="no");
      then
         $step.setTestFailed();
end
         